import type { AIModel } from "@/types/model"

export const models: AIModel[] = [
  {
    id: "openai-gpt-4o",
    slug: "gpt-4o",
    name: "GPT-4o",
    company: "OpenAI",
    accentColor: "#10a37f",
    shortDescription: "Fast multimodal flagship model for text, vision, and voice workflows.",
    description:
      "GPT-4o is a general-purpose multimodal model built for high-quality reasoning, fluent writing, structured outputs, and real-time product experiences across text and vision.",
    categories: ["text-generation", "coding", "research"],
    tags: ["multimodal", "reasoning", "agents", "function calling"],
    bestFor: ["Product assistants", "Multimodal apps", "Writing", "Code help"],
    modalities: ["text", "image", "audio", "code", "multimodal"],
    pricing: { type: "paid", startingPrice: "Usage-based", billingUnit: "tokens" },
    apiAvailable: true,
    openSource: false,
    localRunnable: false,
    contextWindow: 128000,
    releaseDate: "2024-05-13",
    website: "https://openai.com",
    documentation: "https://platform.openai.com/docs",
    featured: true,
    trending: true,
    recentlyAdded: true,
    comparisons: ["claude-3-7-sonnet", "gemini-2-5-pro", "deepseek-r1"],
    strengths: ["Strong multimodal capability", "Mature API platform", "Reliable structured output support"],
    weaknesses: ["Closed weights", "Costs can scale quickly for heavy traffic"],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
  {
    id: "anthropic-claude-3-7-sonnet",
    slug: "claude-3-7-sonnet",
    name: "Claude 3.7 Sonnet",
    company: "Anthropic",
    accentColor: "#d97757",
    shortDescription: "Premium reasoning and coding model with excellent long-form output quality.",
    description:
      "Claude 3.7 Sonnet is designed for careful reasoning, software engineering support, document analysis, and polished long-form writing with a strong developer experience.",
    categories: ["text-generation", "coding", "research"],
    tags: ["reasoning", "coding", "long context", "writing"],
    bestFor: ["Code review", "Complex writing", "Research synthesis", "Agentic workflows"],
    modalities: ["text", "image", "code", "reasoning"],
    pricing: { type: "paid", startingPrice: "Usage-based", billingUnit: "tokens" },
    apiAvailable: true,
    openSource: false,
    localRunnable: false,
    contextWindow: 200000,
    releaseDate: "2025-02-24",
    website: "https://anthropic.com",
    documentation: "https://docs.anthropic.com",
    featured: true,
    trending: true,
    comparisons: ["gpt-4o", "gemini-2-5-pro", "deepseek-r1"],
    strengths: ["Excellent code reasoning", "Clear long-form responses", "Large context window"],
    weaknesses: ["Closed weights", "Some features vary by platform"],
    speed: "moderate",
    lastUpdated: "2026-05-14",
  },
  {
    id: "google-gemini-2-5-pro",
    slug: "gemini-2-5-pro",
    name: "Gemini 2.5 Pro",
    company: "Google DeepMind",
    accentColor: "#4285f4",
    shortDescription: "High-context multimodal model for reasoning, research, and Google ecosystem apps.",
    description:
      "Gemini 2.5 Pro is a frontier multimodal model suited to long-context analysis, research-heavy workflows, and applications that benefit from Google platform integrations.",
    categories: ["text-generation", "coding", "research"],
    tags: ["long context", "multimodal", "reasoning", "google"],
    bestFor: ["Long document analysis", "Research", "Workspace workflows", "Coding"],
    modalities: ["text", "image", "video", "code", "reasoning", "multimodal"],
    pricing: { type: "paid", startingPrice: "Usage-based", billingUnit: "tokens" },
    apiAvailable: true,
    openSource: false,
    localRunnable: false,
    contextWindow: 1000000,
    releaseDate: "2025-03-25",
    website: "https://deepmind.google",
    documentation: "https://ai.google.dev",
    featured: true,
    trending: true,
    comparisons: ["gpt-4o", "claude-3-7-sonnet", "deepseek-r1"],
    strengths: ["Very large context options", "Strong multimodal input support", "Good fit for research workflows"],
    weaknesses: ["Closed weights", "Product availability can differ by region and tier"],
    speed: "moderate",
    lastUpdated: "2026-05-14",
  },
  {
    id: "deepseek-r1",
    slug: "deepseek-r1",
    name: "DeepSeek R1",
    company: "DeepSeek",
    accentColor: "#4f46e5",
    shortDescription: "Reasoning-focused model popular for math, coding, and open-weight deployment.",
    description:
      "DeepSeek R1 emphasizes stepwise reasoning and competitive coding/math performance, with open-weight variants that make it attractive for experimentation and self-hosting.",
    categories: ["text-generation", "coding", "research", "open-source"],
    tags: ["reasoning", "open weights", "math", "coding"],
    bestFor: ["Reasoning tasks", "Math", "Self-hosted assistants", "Coding experiments"],
    modalities: ["text", "code", "reasoning"],
    pricing: { type: "freemium", startingPrice: "Varies by host" },
    apiAvailable: true,
    openSource: true,
    localRunnable: true,
    contextWindow: 128000,
    releaseDate: "2025-01-20",
    website: "https://www.deepseek.com",
    documentation: "https://api-docs.deepseek.com",
    featured: true,
    trending: true,
    comparisons: ["gpt-4o", "claude-3-7-sonnet", "qwen"],
    strengths: ["Strong reasoning value", "Open-weight options", "Good coding and math utility"],
    weaknesses: ["Operational quality depends on host", "May require more tuning for product polish"],
    speed: "moderate",
    lastUpdated: "2026-05-14",
  },
  {
    id: "meta-llama-3",
    slug: "llama-3",
    name: "Llama 3",
    company: "Meta",
    accentColor: "#2563eb",
    shortDescription: "Widely adopted open model family for local and hosted AI applications.",
    description:
      "Llama 3 is a flexible open model family used across chatbots, enterprise prototypes, local apps, and fine-tuned domain systems.",
    categories: ["text-generation", "coding", "open-source"],
    tags: ["open weights", "fine-tuning", "local", "self-hosting"],
    bestFor: ["Self-hosting", "Fine-tuning", "Privacy-sensitive workflows", "Prototyping"],
    modalities: ["text", "code"],
    pricing: { type: "free", notes: "Hosting and inference costs vary." },
    apiAvailable: true,
    openSource: true,
    localRunnable: true,
    contextWindow: 128000,
    releaseDate: "2024-04-18",
    website: "https://ai.meta.com/llama",
    documentation: "https://llama.meta.com",
    featured: true,
    comparisons: ["mistral-large", "qwen", "deepseek-r1"],
    strengths: ["Broad ecosystem support", "Open-weight deployment", "Good fine-tuning base"],
    weaknesses: ["Requires hosting expertise", "Frontier closed models may outperform on some tasks"],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
  {
    id: "black-forest-labs-flux",
    slug: "flux",
    name: "FLUX",
    company: "Black Forest Labs",
    accentColor: "#111827",
    shortDescription: "High-quality image generation family with strong prompt adherence.",
    description:
      "FLUX is an image generation model family known for crisp visual quality, typography improvements, and strong composition control across creative and commercial use cases.",
    categories: ["image-generation", "open-source"],
    tags: ["image", "open weights", "design", "prompt adherence"],
    bestFor: ["Marketing visuals", "Concept art", "Product mockups", "Local image workflows"],
    modalities: ["text", "image"],
    pricing: { type: "freemium", startingPrice: "Varies by edition and host" },
    apiAvailable: true,
    openSource: true,
    localRunnable: true,
    releaseDate: "2024-08-01",
    website: "https://blackforestlabs.ai",
    featured: true,
    trending: true,
    comparisons: ["midjourney", "sdxl"],
    strengths: ["Strong image quality", "Local-capable variants", "Good prompt adherence"],
    weaknesses: ["Hardware demands can be high", "Licensing differs by variant"],
    speed: "moderate",
    lastUpdated: "2026-05-14",
  },
  {
    id: "midjourney",
    slug: "midjourney",
    name: "Midjourney",
    company: "Midjourney",
    accentColor: "#8b5cf6",
    shortDescription: "Premium image generation product for expressive, high-style visuals.",
    description:
      "Midjourney is a polished image generation platform favored by designers, artists, and teams that need striking visuals without managing inference infrastructure.",
    categories: ["image-generation"],
    tags: ["image", "art direction", "design", "discord"],
    bestFor: ["Art direction", "Moodboards", "Editorial visuals", "Creative exploration"],
    modalities: ["text", "image"],
    pricing: { type: "paid", startingPrice: "Subscription" },
    apiAvailable: false,
    openSource: false,
    localRunnable: false,
    releaseDate: "2022-07-12",
    website: "https://www.midjourney.com",
    featured: true,
    trending: true,
    comparisons: ["flux", "sdxl"],
    strengths: ["Distinctive visual quality", "Fast creative iteration", "Strong community workflows"],
    weaknesses: ["No broadly available official API", "Closed model"],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
  {
    id: "stability-sdxl",
    slug: "sdxl",
    name: "SDXL",
    company: "Stability AI",
    accentColor: "#0ea5e9",
    shortDescription: "Open image generation base model with a large fine-tuning ecosystem.",
    description:
      "SDXL remains a common open image foundation for custom styles, local workflows, and specialized pipelines built around ControlNet and community tooling.",
    categories: ["image-generation", "open-source"],
    tags: ["open weights", "image", "fine-tuning", "local"],
    bestFor: ["Custom styles", "Local image generation", "ControlNet pipelines", "Fine-tuned visual systems"],
    modalities: ["text", "image"],
    pricing: { type: "free", notes: "Hosting and GPU costs vary." },
    apiAvailable: true,
    openSource: true,
    localRunnable: true,
    releaseDate: "2023-07-26",
    website: "https://stability.ai",
    documentation: "https://platform.stability.ai/docs",
    comparisons: ["flux", "midjourney"],
    strengths: ["Large ecosystem", "Flexible local workflows", "Many fine-tuned variants"],
    weaknesses: ["Can need prompt tuning", "Quality depends heavily on workflow"],
    speed: "moderate",
    lastUpdated: "2026-05-14",
  },
  {
    id: "kuaishou-kling",
    slug: "kling",
    name: "Kling",
    company: "Kuaishou",
    accentColor: "#f97316",
    shortDescription: "Video generation model known for cinematic motion and image-to-video quality.",
    description:
      "Kling is a video generation system for text-to-video and image-to-video work, often used for cinematic clips, ad concepts, and motion experiments.",
    categories: ["video-generation"],
    tags: ["video", "image-to-video", "motion", "cinematic"],
    bestFor: ["Short cinematic clips", "Ad concepts", "Image animation", "Creative video tests"],
    modalities: ["text", "image", "video"],
    pricing: { type: "freemium", startingPrice: "Credits" },
    apiAvailable: true,
    openSource: false,
    localRunnable: false,
    releaseDate: "2024-06-06",
    website: "https://klingai.com",
    featured: true,
    trending: true,
    comparisons: ["runway"],
    strengths: ["Strong motion quality", "Good image-to-video workflows", "Cinematic output"],
    weaknesses: ["Generation queues and limits can vary", "Closed model"],
    speed: "slow",
    lastUpdated: "2026-05-14",
  },
  {
    id: "runway-gen",
    slug: "runway",
    name: "Runway",
    company: "Runway",
    accentColor: "#14b8a6",
    shortDescription: "Creative video platform with generation, editing, and production tools.",
    description:
      "Runway combines video generation models with a production-focused web editor, making it useful for teams that need ideation, editing, and delivery in one workflow.",
    categories: ["video-generation"],
    tags: ["video", "editor", "creative suite", "image-to-video"],
    bestFor: ["Creative teams", "Video ideation", "Production workflows", "Commercial storyboards"],
    modalities: ["text", "image", "video"],
    pricing: { type: "freemium", startingPrice: "Subscription" },
    apiAvailable: true,
    openSource: false,
    localRunnable: false,
    releaseDate: "2023-03-20",
    website: "https://runwayml.com",
    documentation: "https://docs.dev.runwayml.com",
    featured: true,
    comparisons: ["kling"],
    strengths: ["Strong product workflow", "Editing tools included", "Team-friendly interface"],
    weaknesses: ["Closed system", "Credit costs can matter for iteration-heavy teams"],
    speed: "slow",
    lastUpdated: "2026-05-14",
  },
  {
    id: "elevenlabs",
    slug: "elevenlabs",
    name: "ElevenLabs",
    company: "ElevenLabs",
    accentColor: "#6366f1",
    shortDescription: "High-quality voice AI for speech synthesis, dubbing, and agents.",
    description:
      "ElevenLabs provides voice generation, voice cloning, dubbing, and speech tools for creators and products that need natural spoken audio.",
    categories: ["audio"],
    tags: ["voice", "speech", "dubbing", "agents"],
    bestFor: ["Narration", "Voice agents", "Localization", "Creator audio"],
    modalities: ["text", "audio"],
    pricing: { type: "freemium", startingPrice: "Subscription and usage tiers" },
    apiAvailable: true,
    openSource: false,
    localRunnable: false,
    releaseDate: "2023-01-30",
    website: "https://elevenlabs.io",
    documentation: "https://elevenlabs.io/docs",
    featured: true,
    trending: true,
    comparisons: ["suno"],
    strengths: ["Natural voice quality", "Strong API", "Broad creator and product use cases"],
    weaknesses: ["Closed model", "Voice rights and consent need careful governance"],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
  {
    id: "suno",
    slug: "suno",
    name: "Suno",
    company: "Suno",
    accentColor: "#ec4899",
    shortDescription: "Music generation platform for songs, lyrics, and rapid audio concepts.",
    description:
      "Suno helps users generate complete songs and musical ideas from prompts, making it useful for drafts, demos, and creative experimentation.",
    categories: ["music", "audio"],
    tags: ["music", "songs", "lyrics", "creator"],
    bestFor: ["Song ideas", "Demos", "Creator content", "Audio experimentation"],
    modalities: ["text", "music", "audio"],
    pricing: { type: "freemium", startingPrice: "Subscription" },
    apiAvailable: false,
    openSource: false,
    localRunnable: false,
    releaseDate: "2023-12-20",
    website: "https://suno.com",
    featured: true,
    trending: true,
    comparisons: ["elevenlabs"],
    strengths: ["Fast full-song generation", "Accessible creative UX", "Good for ideation"],
    weaknesses: ["Limited production control compared with DAWs", "Closed platform"],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
  {
    id: "cursor",
    slug: "cursor",
    name: "Cursor",
    company: "Anysphere",
    accentColor: "#111827",
    shortDescription: "AI-native code editor for pair programming, refactors, and codebase Q&A.",
    description:
      "Cursor is a developer tool built around AI-assisted editing, repo-aware chat, refactoring, and coding workflows inside a VS Code-like environment.",
    categories: ["coding"],
    tags: ["code editor", "agent", "refactor", "developer tools"],
    bestFor: ["Codebase navigation", "Refactors", "Feature implementation", "Developer productivity"],
    modalities: ["text", "code"],
    pricing: { type: "freemium", startingPrice: "Subscription" },
    apiAvailable: false,
    openSource: false,
    localRunnable: false,
    releaseDate: "2023-03-01",
    website: "https://cursor.com",
    featured: true,
    trending: true,
    comparisons: ["devin", "claude-3-7-sonnet"],
    strengths: ["Excellent editor workflow", "Repo-aware assistance", "Practical coding UX"],
    weaknesses: ["Not a standalone foundation model", "Best value depends on supported model choices"],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
  {
    id: "cognition-devin",
    slug: "devin",
    name: "Devin",
    company: "Cognition",
    accentColor: "#22c55e",
    shortDescription: "Autonomous software engineering agent for multi-step development tasks.",
    description:
      "Devin is positioned as a software engineering agent that can plan, edit, run commands, and work through larger implementation tasks with less manual prompting.",
    categories: ["coding"],
    tags: ["software agent", "automation", "coding", "planning"],
    bestFor: ["Multi-step coding tasks", "Issue implementation", "Engineering automation", "Repo maintenance"],
    modalities: ["text", "code", "reasoning"],
    pricing: { type: "paid", startingPrice: "Subscription" },
    apiAvailable: false,
    openSource: false,
    localRunnable: false,
    releaseDate: "2024-03-12",
    website: "https://devin.ai",
    featured: true,
    comparisons: ["cursor", "claude-3-7-sonnet"],
    strengths: ["Agentic workflow", "Can execute development loops", "Good fit for delegated tasks"],
    weaknesses: ["Closed platform", "Requires careful task scoping and review"],
    speed: "slow",
    lastUpdated: "2026-05-14",
  },
  {
    id: "mistral-large",
    slug: "mistral-large",
    name: "Mistral Large",
    company: "Mistral AI",
    accentColor: "#ff7000",
    shortDescription: "European frontier model family with strong multilingual and enterprise API options.",
    description:
      "Mistral Large is a capable commercial model for reasoning, multilingual assistants, enterprise deployments, and teams that want a strong European AI provider.",
    categories: ["text-generation", "coding"],
    tags: ["multilingual", "enterprise", "api", "reasoning"],
    bestFor: ["Enterprise assistants", "Multilingual workflows", "EU-focused deployments", "Coding support"],
    modalities: ["text", "code", "reasoning"],
    pricing: { type: "paid", startingPrice: "Usage-based", billingUnit: "tokens" },
    apiAvailable: true,
    openSource: false,
    localRunnable: false,
    contextWindow: 128000,
    releaseDate: "2024-02-26",
    website: "https://mistral.ai",
    documentation: "https://docs.mistral.ai",
    comparisons: ["llama-3", "qwen", "gpt-4o"],
    strengths: ["Strong multilingual support", "Enterprise-friendly positioning", "Clean API"],
    weaknesses: ["Closed flagship weights", "Ecosystem smaller than some larger platforms"],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
  {
    id: "xai-grok",
    slug: "grok",
    name: "Grok",
    company: "xAI",
    accentColor: "#64748b",
    shortDescription: "Conversational model family with real-time social context in xAI products.",
    description:
      "Grok is a conversational model family from xAI, often associated with real-time information workflows and integration into X-based product experiences.",
    categories: ["text-generation", "research"],
    tags: ["chat", "real-time", "social context", "reasoning"],
    bestFor: ["Conversational search", "Social trend analysis", "General chat", "Current event exploration"],
    modalities: ["text", "image", "reasoning"],
    pricing: { type: "freemium", startingPrice: "Subscription and usage tiers" },
    apiAvailable: true,
    openSource: false,
    localRunnable: false,
    contextWindow: 131000,
    releaseDate: "2023-11-04",
    website: "https://x.ai",
    documentation: "https://docs.x.ai",
    comparisons: ["gpt-4o", "gemini-2-5-pro"],
    strengths: ["Real-time product positioning", "Useful for trend-aware chat", "API availability"],
    weaknesses: ["Closed weights", "Best experience may depend on xAI ecosystem access"],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
  {
    id: "alibaba-qwen",
    slug: "qwen",
    name: "Qwen",
    company: "Alibaba Cloud",
    accentColor: "#7c3aed",
    shortDescription: "Open and commercial model family with strong multilingual and coding coverage.",
    description:
      "Qwen is a broad model family with open-weight releases and hosted APIs, spanning chat, coding, math, vision, and multilingual applications.",
    categories: ["text-generation", "coding", "open-source"],
    tags: ["open weights", "multilingual", "coding", "math"],
    bestFor: ["Self-hosted chat", "Coding", "Multilingual products", "Fine-tuning"],
    modalities: ["text", "image", "code", "reasoning"],
    pricing: { type: "freemium", startingPrice: "Varies by host" },
    apiAvailable: true,
    openSource: true,
    localRunnable: true,
    contextWindow: 128000,
    releaseDate: "2023-08-03",
    website: "https://qwenlm.github.io",
    documentation: "https://help.aliyun.com/zh/model-studio",
    featured: true,
    comparisons: ["llama-3", "mistral-large", "deepseek-r1"],
    strengths: ["Strong open ecosystem", "Good multilingual coverage", "Useful coding variants"],
    weaknesses: ["Variant selection can be confusing", "Hosting quality varies"],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
]
