import type { AIModel } from "@/types/model";

const imageGenerationModels: AIModel[] = [
  {
    id: "adobe-firefly-image-3",
    slug: "firefly-image-3",
    name: "Firefly Image 3",
    company: "Adobe",
    accentColor: "#FF0000",
    logo: "adobe.svg",
    shortDescription:
      "Commercial generative AI model optimized for creative production with photorealistic results.",
    description:
      "Firefly Image 3 offers improved generation quality, better detail depiction, photorealism, prompt understanding, and reference image handling for photos, art, and illustrations. Trained on licensed Adobe Stock content.",
    categories: ["image-generation"],
    tags: ["commercial", "photorealistic", "creative", "text-rendering"],
    bestFor: [
      "Professional design",
      "Marketing visuals",
      "Adobe workflows",
      "Customization",
    ],
    modalities: ["text", "image"],
    pricing: {
      type: "paid",
      startingPrice: "Subscription via Adobe",
      billingUnit: "credits",
    },
    apiAvailable: true,
    openSource: false,
    localRunnable: false,
    contextWindow: null,
    releaseDate: "2024-07-21",
    website: "https://firefly.adobe.com",
    documentation:
      "https://developer.adobe.com/firefly-services/docs/firefly-api/",
    featured: true,
    trending: true,
    comparisons: ["flux", "sdxl", "midjourney"],
    strengths: [
      "Excellent integration with Adobe tools",
      "Safe commercial use (trained on licensed data)",
      "Strong photorealism and detail",
      "Improved text rendering and composition",
    ],
    weaknesses: [
      "Adobe ecosystem lock-in",
      "Credit-based pricing limits volume",
    ],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
  {
    id: "deepseek-janus-pro",
    slug: "janus-pro",
    name: "Janus Pro",
    company: "DeepSeek",
    accentColor: "#4f46e5",
    logo: "deepseek.svg",
    shortDescription:
      "Multimodal 7B model for image understanding and text-to-image generation.",
    description:
      "Janus Pro is a unified 7B parameter model excelling in multimodal tasks including high-quality text-to-image at 384x384 resolution.",
    categories: ["image-generation"],
    tags: ["multimodal", "open-weights", "efficient", "understanding"],
    bestFor: ["Multimodal apps", "Reasoning+generation", "Compact deployment"],
    modalities: ["text", "image", "multimodal"],
    pricing: {
      type: "free",
      notes: "Open weights, hosting varies",
    },
    apiAvailable: true,
    openSource: true,
    localRunnable: true,
    contextWindow: null,
    releaseDate: "2025-01-27",
    website: "https://www.deepseek.com",
    documentation: "https://platform.deepseek.com/docs",
    featured: true,
    trending: true,
    comparisons: ["deepseek-r1", "qwen", "llama-3"],
    strengths: [
      "Unified multimodal capabilities",
      "SOTA understanding+generation",
      "Compact 7B size",
      "Open source",
    ],
    weaknesses: ["384x384 res limit", "Early stage tuning needed"],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
  {
    id: "luma-photon",
    slug: "luma-photon",
    name: "Luma Photon",
    company: "Luma AI",
    accentColor: "#ec4899",
    logo: "luma.svg",
    shortDescription:
      "Universal Transformer-based model for artifact-free 1080p image generation.",
    description:
      "Luma Photon generates ultra-high-quality 1080p images with strong prompt adherence, multi-image reference, and character consistency using transformer architecture.",
    categories: ["image-generation"],
    tags: ["1080p", "transformer", "multi-image", "consistency"],
    bestFor: [
      "High-res visuals",
      "Design iteration",
      "Character design",
      "Professional output",
    ],
    modalities: ["text", "image"],
    pricing: {
      type: "paid",
      startingPrice: "Usage-based",
    },
    apiAvailable: true,
    openSource: false,
    localRunnable: false,
    contextWindow: null,
    releaseDate: "2025-10-01",
    website: "https://lumalabs.ai/photon",
    documentation: "https://docs.lumalabs.ai",
    featured: true,
    trending: true,
    comparisons: ["kling", "runway", "flux"],
    strengths: [
      "Artifact-free high-res",
      "Multi-image support",
      "Prompt fidelity",
      "Fast 1080p generation",
    ],
    weaknesses: ["Newer model, ecosystem building", "Pricing for volume"],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
  {
    id: "hidream-i1-dev",
    slug: "hidream-i1-dev",
    name: "HiDream-I1-Dev",
    company: "HiDream AI",
    accentColor: "#8b5cf6",
    logo: "hidream.svg",
    shortDescription:
      "Open-source 17B parameter image foundation model with efficient diffusion transformer.",
    description:
      "HiDream-I1-Dev is a distilled variant balancing quality and speed (28 steps), achieving SOTA image generation. Full model uses 50+ steps for max fidelity.",
    categories: ["image-generation", "open-source"],
    tags: ["open-source", "foundation-model", "efficient", "high-fidelity"],
    bestFor: [
      "Self-hosting",
      "Research",
      "Custom fine-tuning",
      "Iterative workflows",
    ],
    modalities: ["text", "image"],
    pricing: {
      type: "free",
      notes: "Hosting/GPU costs apply",
    },
    apiAvailable: false,
    openSource: true,
    localRunnable: true,
    contextWindow: null,
    releaseDate: "2025-05-27",
    website: "https://huggingface.co/collections/HiDream-I1",
    documentation: "https://arxiv.org/abs/2505.22705",
    featured: true,
    trending: true,
    comparisons: ["flux", "sdxl", "deepseek-r1"],
    strengths: [
      "State-of-the-art open quality",
      "Sparse diffusion efficiency",
      "17B parameters accessible",
      "Multiple variants (Dev/Fast/Full)",
    ],
    weaknesses: ["High VRAM needs (16-48GB)", "Self-hosting required"],
    speed: "moderate",
    lastUpdated: "2026-05-14",
  },
  {
    id: "recraft-v4",
    slug: "recraft-v4",
    name: "Recraft V4",
    company: "Recraft",
    accentColor: "#14b8b6",
    logo: "recraft.svg",
    shortDescription:
      "Professional vector and raster image generator for design teams.",
    description:
      "Recraft V4 specializes in commercial-ready vector graphics, logos, icons, and photorealistic images from text prompts, with conversational refinement.",
    categories: ["image-generation"],
    tags: ["vector", "design", "professional", "scalable"],
    bestFor: ["Logos", "Icons", "Product mockups", "Marketing assets"],
    modalities: ["text", "image"],
    pricing: {
      type: "freemium",
      startingPrice: "Subscription",
    },
    apiAvailable: true,
    openSource: false,
    localRunnable: false,
    contextWindow: null,
    releaseDate: "2025-06-01",
    website: "https://www.recraft.ai",
    documentation: "https://www.recraft.ai/docs",
    featured: true,
    trending: true,
    comparisons: ["ideogram-v3", "firefly-image-3", "sdxl"],
    strengths: [
      "Vector output support",
      "Conversational editing",
      "Professional polish",
      "Scalable graphics",
    ],
    weaknesses: [
      "Vector focus limits photorealism breadth",
      "Subscription required for high volume",
    ],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
  {
    id: "ideogram-v3",
    slug: "ideogram-v3",
    name: "Ideogram 3.0",
    company: "Ideogram",
    accentColor: "#6366f1",
    logo: "ideogram.svg",
    shortDescription:
      "Text-to-image model excelling in typography, text rendering, and graphic design.",
    description:
      "Ideogram 3.0 (V3) generates photorealistic images with accurate in-image text, style reference control, and tiers for speed vs quality tradeoff. Supports up to 10,000 token prompts.",
    categories: ["image-generation"],
    tags: ["typography", "text-in-image", "design", "photorealistic"],
    bestFor: [
      "Logos",
      "Posters",
      "Marketing graphics",
      "Typography-heavy designs",
    ],
    modalities: ["text", "image"],
    pricing: {
      type: "freemium",
      startingPrice: "Credits",
    },
    apiAvailable: true,
    openSource: false,
    localRunnable: false,
    contextWindow: 10000,
    releaseDate: "2025-03-01",
    website: "https://ideogram.ai",
    documentation: "https://docs.ideogram.ai",
    featured: true,
    trending: true,
    comparisons: ["flux", "recraft-v4", "firefly-image-3"],
    strengths: [
      "Best-in-class text rendering",
      "Style reference support",
      "Multiple quality tiers",
      "Graphic design focus",
    ],
    weaknesses: [
      "Limited to specific use cases",
      "Generation queues during peaks",
    ],
    speed: "moderate",
    lastUpdated: "2026-05-14",
  },
  {
    id: "stability-sdxl",
    slug: "sdxl",
    name: "SDXL",
    company: "Stability AI",
    accentColor: "#0ea5e9",
    logo: "stability.svg",
    shortDescription:
      "Open image generation base model with a large fine-tuning ecosystem.",
    description:
      "SDXL remains a common open image foundation for custom styles, local workflows, and specialized pipelines built around ControlNet and community tooling.",
    categories: ["image-generation", "open-source"],
    tags: ["open weights", "image", "fine-tuning", "local"],
    bestFor: [
      "Custom styles",
      "Local image generation",
      "ControlNet pipelines",
      "Fine-tuned visual systems",
    ],
    modalities: ["text", "image"],
    pricing: { type: "free", notes: "Hosting and GPU costs vary." },
    apiAvailable: true,
    openSource: true,
    localRunnable: true,
    releaseDate: "2023-07-26",
    website: "https://stability.ai",
    documentation: "https://platform.stability.ai/docs",
    comparisons: ["flux", "midjourney"],
    strengths: [
      "Large ecosystem",
      "Flexible local workflows",
      "Many fine-tuned variants",
    ],
    weaknesses: [
      "Can need prompt tuning",
      "Quality depends heavily on workflow",
    ],
    speed: "moderate",
    lastUpdated: "2026-05-14",
  },
  {
    id: "midjourney",
    slug: "midjourney",
    name: "Midjourney",
    company: "Midjourney",
    accentColor: "#8b5cf6",
    logo: "midjourney.svg",
    shortDescription:
      "Premium image generation product for expressive, high-style visuals.",
    description:
      "Midjourney is a polished image generation platform favored by designers, artists, and teams that need striking visuals without managing inference infrastructure.",
    categories: ["image-generation"],
    tags: ["image", "art direction", "design", "discord"],
    bestFor: [
      "Art direction",
      "Moodboards",
      "Editorial visuals",
      "Creative exploration",
    ],
    modalities: ["text", "image"],
    pricing: { type: "paid", startingPrice: "Subscription" },
    apiAvailable: false,
    openSource: false,
    localRunnable: false,
    releaseDate: "2022-07-12",
    website: "https://www.midjourney.com",
    featured: true,
    trending: true,
    comparisons: ["flux", "sdxl"],
    strengths: [
      "Distinctive visual quality",
      "Fast creative iteration",
      "Strong community workflows",
    ],
    weaknesses: ["No broadly available official API", "Closed model"],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
  {
    id: "black-forest-labs-flux",
    slug: "flux",
    name: "FLUX",
    company: "Black Forest Labs",
    accentColor: "#111827",
    logo: "flux.svg",
    shortDescription:
      "High-quality image generation family with strong prompt adherence.",
    description:
      "FLUX is an image generation model family known for crisp visual quality, typography improvements, and strong composition control across creative and commercial use cases.",
    categories: ["image-generation", "open-source"],
    tags: ["image", "open weights", "design", "prompt adherence"],
    bestFor: [
      "Marketing visuals",
      "Concept art",
      "Product mockups",
      "Local image workflows",
    ],
    modalities: ["text", "image"],
    pricing: { type: "freemium", startingPrice: "Varies by edition and host" },
    apiAvailable: true,
    openSource: true,
    localRunnable: true,
    releaseDate: "2024-08-01",
    website: "https://blackforestlabs.ai",
    featured: true,
    trending: true,
    comparisons: ["midjourney", "sdxl"],
    strengths: [
      "Strong image quality",
      "Local-capable variants",
      "Good prompt adherence",
    ],
    weaknesses: [
      "Hardware demands can be high",
      "Licensing differs by variant",
    ],
    speed: "moderate",
    lastUpdated: "2026-05-14",
  },
];

const videoGenerationModels: AIModel[] = [
  {
    id: "kuaishou-kling",
    slug: "kling",
    name: "Kling",
    company: "Kuaishou",
    accentColor: "#f97316",
    logo: "kling.svg",
    shortDescription:
      "Video generation model known for cinematic motion and image-to-video quality.",
    description:
      "Kling is a video generation system for text-to-video and image-to-video work, often used for cinematic clips, ad concepts, and motion experiments.",
    categories: ["video-generation"],
    tags: ["video", "image-to-video", "motion", "cinematic"],
    bestFor: [
      "Short cinematic clips",
      "Ad concepts",
      "Image animation",
      "Creative video tests",
    ],
    modalities: ["text", "image", "video"],
    pricing: { type: "freemium", startingPrice: "Credits" },
    apiAvailable: true,
    openSource: false,
    localRunnable: false,
    releaseDate: "2024-06-06",
    website: "https://klingai.com",
    featured: true,
    trending: true,
    comparisons: ["runway"],
    strengths: [
      "Strong motion quality",
      "Good image-to-video workflows",
      "Cinematic output",
    ],
    weaknesses: ["Generation queues and limits can vary", "Closed model"],
    speed: "slow",
    lastUpdated: "2026-05-14",
  },
  {
    id: "runway-gen",
    slug: "runway",
    name: "Runway",
    company: "Runway",
    accentColor: "#14b8a6",
    logo: "runway.svg",
    shortDescription:
      "Creative video platform with generation, editing, and production tools.",
    description:
      "Runway combines video generation models with a production-focused web editor, making it useful for teams that need ideation, editing, and delivery in one workflow.",
    categories: ["video-generation"],
    tags: ["video", "editor", "creative suite", "image-to-video"],
    bestFor: [
      "Creative teams",
      "Video ideation",
      "Production workflows",
      "Commercial storyboards",
    ],
    modalities: ["text", "image", "video"],
    pricing: { type: "freemium", startingPrice: "Subscription" },
    apiAvailable: true,
    openSource: false,
    localRunnable: false,
    releaseDate: "2023-03-20",
    website: "https://runwayml.com",
    documentation: "https://docs.dev.runwayml.com",
    featured: true,
    comparisons: ["kling"],
    strengths: [
      "Strong product workflow",
      "Editing tools included",
      "Team-friendly interface",
    ],
    weaknesses: [
      "Closed system",
      "Credit costs can matter for iteration-heavy teams",
    ],
    speed: "slow",
    lastUpdated: "2026-05-14",
  },
];

const audioGenerationModels: AIModel[] = [
  {
    id: "elevenlabs",
    slug: "elevenlabs",
    name: "ElevenLabs",
    company: "ElevenLabs",
    accentColor: "#6366f1",
    logo: "elevenlabs.svg",
    shortDescription:
      "High-quality voice AI for speech synthesis, dubbing, and agents.",
    description:
      "ElevenLabs provides voice generation, voice cloning, dubbing, and speech tools for creators and products that need natural spoken audio.",
    categories: ["audio"],
    tags: ["voice", "speech", "dubbing", "agents"],
    bestFor: ["Narration", "Voice agents", "Localization", "Creator audio"],
    modalities: ["text", "audio"],
    pricing: {
      type: "freemium",
      startingPrice: "Subscription and usage tiers",
    },
    apiAvailable: true,
    openSource: false,
    localRunnable: false,
    releaseDate: "2023-01-30",
    website: "https://elevenlabs.io",
    documentation: "https://elevenlabs.io/docs",
    featured: true,
    trending: true,
    comparisons: ["suno"],
    strengths: [
      "Natural voice quality",
      "Strong API",
      "Broad creator and product use cases",
    ],
    weaknesses: [
      "Closed model",
      "Voice rights and consent need careful governance",
    ],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
];

const codingModels: AIModel[] = [
  {
    id: "cursor",
    slug: "cursor",
    name: "Cursor",
    company: "Anysphere",
    accentColor: "#111827",
    logo: "cursor.svg",
    shortDescription:
      "AI-native code editor for pair programming, refactors, and codebase Q&A.",
    description:
      "Cursor is a developer tool built around AI-assisted editing, repo-aware chat, refactoring, and coding workflows inside a VS Code-like environment.",
    categories: ["coding"],
    tags: ["code editor", "agent", "refactor", "developer tools"],
    bestFor: [
      "Codebase navigation",
      "Refactors",
      "Feature implementation",
      "Developer productivity",
    ],
    modalities: ["text", "code"],
    pricing: { type: "freemium", startingPrice: "Subscription" },
    apiAvailable: false,
    openSource: false,
    localRunnable: false,
    releaseDate: "2023-03-01",
    website: "https://cursor.com",
    featured: true,
    trending: true,
    comparisons: ["devin", "claude-3-7-sonnet"],
    strengths: [
      "Excellent editor workflow",
      "Repo-aware assistance",
      "Practical coding UX",
    ],
    weaknesses: [
      "Not a standalone foundation model",
      "Best value depends on supported model choices",
    ],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
  {
    id: "cognition-devin",
    slug: "devin",
    name: "Devin",
    company: "Cognition",
    accentColor: "#22c55e",
    logo: "devin.svg",
    shortDescription:
      "Autonomous software engineering agent for multi-step development tasks.",
    description:
      "Devin is positioned as a software engineering agent that can plan, edit, run commands, and work through larger implementation tasks with less manual prompting.",
    categories: ["coding"],
    tags: ["software agent", "automation", "coding", "planning"],
    bestFor: [
      "Multi-step coding tasks",
      "Issue implementation",
      "Engineering automation",
      "Repo maintenance",
    ],
    modalities: ["text", "code", "reasoning"],
    pricing: { type: "paid", startingPrice: "Subscription" },
    apiAvailable: false,
    openSource: false,
    localRunnable: false,
    releaseDate: "2024-03-12",
    website: "https://devin.ai",
    featured: true,
    comparisons: ["cursor", "claude-3-7-sonnet"],
    strengths: [
      "Agentic workflow",
      "Can execute development loops",
      "Good fit for delegated tasks",
    ],
    weaknesses: ["Closed platform", "Requires careful task scoping and review"],
    speed: "slow",
    lastUpdated: "2026-05-14",
  },
];

const multimodalModels: AIModel[] = [
  {
    id: "openai-gpt-4o",
    slug: "gpt-4o",
    name: "GPT-4o",
    company: "OpenAI",
    accentColor: "#10a37f",
    logo: "open-ai.svg",
    shortDescription:
      "Fast multimodal flagship model for text, vision, and voice workflows.",
    description:
      "GPT-4o is a general-purpose multimodal model built for high-quality reasoning, fluent writing, structured outputs, and real-time product experiences across text and vision.",
    categories: ["text-generation", "coding", "research"],
    tags: ["multimodal", "reasoning", "agents", "function calling"],
    bestFor: ["Product assistants", "Multimodal apps", "Writing", "Code help"],
    modalities: ["text", "image", "audio", "code", "multimodal"],
    pricing: {
      type: "paid",
      startingPrice: "Usage-based",
      billingUnit: "tokens",
    },
    apiAvailable: true,
    openSource: false,
    localRunnable: false,
    contextWindow: 128000,
    releaseDate: "2024-05-13",
    website: "https://openai.com",
    documentation: "https://platform.openai.com/docs",
    featured: true,
    trending: true,
    recentlyAdded: true,
    comparisons: ["claude-3-7-sonnet", "gemini-2-5-pro", "deepseek-r1"],
    strengths: [
      "Strong multimodal capability",
      "Mature API platform",
      "Reliable structured output support",
    ],
    weaknesses: ["Closed weights", "Costs can scale quickly for heavy traffic"],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
  {
    id: "anthropic-claude-3-7-sonnet",
    slug: "claude-3-7-sonnet",
    name: "Claude 3.7 Sonnet",
    company: "Anthropic",
    accentColor: "#d97757",
    logo: "claude.svg",
    shortDescription:
      "Premium reasoning and coding model with excellent long-form output quality.",
    description:
      "Claude 3.7 Sonnet is designed for careful reasoning, software engineering support, document analysis, and polished long-form writing with a strong developer experience.",
    categories: ["text-generation", "coding", "research"],
    tags: ["reasoning", "coding", "long context", "writing"],
    bestFor: [
      "Code review",
      "Complex writing",
      "Research synthesis",
      "Agentic workflows",
    ],
    modalities: ["text", "image", "code", "reasoning"],
    pricing: {
      type: "paid",
      startingPrice: "Usage-based",
      billingUnit: "tokens",
    },
    apiAvailable: true,
    openSource: false,
    localRunnable: false,
    contextWindow: 200000,
    releaseDate: "2025-02-24",
    website: "https://anthropic.com",
    documentation: "https://docs.anthropic.com",
    featured: true,
    trending: true,
    comparisons: ["gpt-4o", "gemini-2-5-pro", "deepseek-r1"],
    strengths: [
      "Excellent code reasoning",
      "Clear long-form responses",
      "Large context window",
    ],
    weaknesses: ["Closed weights", "Some features vary by platform"],
    speed: "moderate",
    lastUpdated: "2026-05-14",
  },
  {
    id: "google-gemini-2-5-pro",
    slug: "gemini-2-5-pro",
    name: "Gemini 2.5 Pro",
    company: "Google DeepMind",
    accentColor: "#4285f4",
    logo: "gemini.svg",
    shortDescription:
      "High-context multimodal model for reasoning, research, and Google ecosystem apps.",
    description:
      "Gemini 2.5 Pro is a frontier multimodal model suited to long-context analysis, research-heavy workflows, and applications that benefit from Google platform integrations.",
    categories: ["text-generation", "coding", "research"],
    tags: ["long context", "multimodal", "reasoning", "google"],
    bestFor: [
      "Long document analysis",
      "Research",
      "Workspace workflows",
      "Coding",
    ],
    modalities: ["text", "image", "video", "code", "reasoning", "multimodal"],
    pricing: {
      type: "paid",
      startingPrice: "Usage-based",
      billingUnit: "tokens",
    },
    apiAvailable: true,
    openSource: false,
    localRunnable: false,
    contextWindow: 1000000,
    releaseDate: "2025-03-25",
    website: "https://deepmind.google",
    documentation: "https://ai.google.dev",
    featured: true,
    trending: true,
    comparisons: ["gpt-4o", "claude-3-7-sonnet", "deepseek-r1"],
    strengths: [
      "Very large context options",
      "Strong multimodal input support",
      "Good fit for research workflows",
    ],
    weaknesses: [
      "Closed weights",
      "Product availability can differ by region and tier",
    ],
    speed: "moderate",
    lastUpdated: "2026-05-14",
  },
  {
    id: "deepseek-r1",
    slug: "deepseek-r1",
    name: "DeepSeek R1",
    company: "DeepSeek",
    accentColor: "#4f46e5",
    logo: "deepseek.svg",
    shortDescription:
      "Reasoning-focused model popular for math, coding, and open-weight deployment.",
    description:
      "DeepSeek R1 emphasizes stepwise reasoning and competitive coding/math performance, with open-weight variants that make it attractive for experimentation and self-hosting.",
    categories: ["text-generation", "coding", "research", "open-source"],
    tags: ["reasoning", "open weights", "math", "coding"],
    bestFor: [
      "Reasoning tasks",
      "Math",
      "Self-hosted assistants",
      "Coding experiments",
    ],
    modalities: ["text", "code", "reasoning"],
    pricing: { type: "freemium", startingPrice: "Varies by host" },
    apiAvailable: true,
    openSource: true,
    localRunnable: true,
    contextWindow: 128000,
    releaseDate: "2025-01-20",
    website: "https://www.deepseek.com",
    documentation: "https://api-docs.deepseek.com",
    featured: true,
    trending: true,
    comparisons: ["gpt-4o", "claude-3-7-sonnet", "qwen"],
    strengths: [
      "Strong reasoning value",
      "Open-weight options",
      "Good coding and math utility",
    ],
    weaknesses: [
      "Operational quality depends on host",
      "May require more tuning for product polish",
    ],
    speed: "moderate",
    lastUpdated: "2026-05-14",
  },
  {
    id: "meta-llama-3",
    slug: "llama-3",
    name: "Llama 3",
    company: "Meta",
    accentColor: "#2563eb",
    logo: "llama.svg",
    shortDescription:
      "Widely adopted open model family for local and hosted AI applications.",
    description:
      "Llama 3 is a flexible open model family used across chatbots, enterprise prototypes, local apps, and fine-tuned domain systems.",
    categories: ["text-generation", "coding", "open-source"],
    tags: ["open weights", "fine-tuning", "local", "self-hosting"],
    bestFor: [
      "Self-hosting",
      "Fine-tuning",
      "Privacy-sensitive workflows",
      "Prototyping",
    ],
    modalities: ["text", "code"],
    pricing: { type: "free", notes: "Hosting and inference costs vary." },
    apiAvailable: true,
    openSource: true,
    localRunnable: true,
    contextWindow: 128000,
    releaseDate: "2024-04-18",
    website: "https://ai.meta.com/llama",
    documentation: "https://llama.meta.com",
    featured: true,
    comparisons: ["mistral-large", "qwen", "deepseek-r1"],
    strengths: [
      "Broad ecosystem support",
      "Open-weight deployment",
      "Good fine-tuning base",
    ],
    weaknesses: [
      "Requires hosting expertise",
      "Frontier closed models may outperform on some tasks",
    ],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
  {
    id: "suno",
    slug: "suno",
    name: "Suno",
    company: "Suno",
    accentColor: "#ec4899",
    logo: "suno.svg",
    shortDescription:
      "Music generation platform for songs, lyrics, and rapid audio concepts.",
    description:
      "Suno helps users generate complete songs and musical ideas from prompts, making it useful for drafts, demos, and creative experimentation.",
    categories: ["music", "audio"],
    tags: ["music", "songs", "lyrics", "creator"],
    bestFor: [
      "Song ideas",
      "Demos",
      "Creator content",
      "Audio experimentation",
    ],
    modalities: ["text", "music", "audio"],
    pricing: { type: "freemium", startingPrice: "Subscription" },
    apiAvailable: false,
    openSource: false,
    localRunnable: false,
    releaseDate: "2023-12-20",
    website: "https://suno.com",
    featured: true,
    trending: true,
    comparisons: ["elevenlabs"],
    strengths: [
      "Fast full-song generation",
      "Accessible creative UX",
      "Good for ideation",
    ],
    weaknesses: [
      "Limited production control compared with DAWs",
      "Closed platform",
    ],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
  {
    id: "mistral-large",
    slug: "mistral-large",
    name: "Mistral Large",
    company: "Mistral AI",
    accentColor: "#ff7000",
    logo: "mistral.svg",
    shortDescription:
      "European frontier model family with strong multilingual and enterprise API options.",
    description:
      "Mistral Large is a capable commercial model for reasoning, multilingual assistants, enterprise deployments, and teams that want a strong European AI provider.",
    categories: ["text-generation", "coding"],
    tags: ["multilingual", "enterprise", "api", "reasoning"],
    bestFor: [
      "Enterprise assistants",
      "Multilingual workflows",
      "EU-focused deployments",
      "Coding support",
    ],
    modalities: ["text", "code", "reasoning"],
    pricing: {
      type: "paid",
      startingPrice: "Usage-based",
      billingUnit: "tokens",
    },
    apiAvailable: true,
    openSource: false,
    localRunnable: false,
    contextWindow: 128000,
    releaseDate: "2024-02-26",
    website: "https://mistral.ai",
    documentation: "https://docs.mistral.ai",
    comparisons: ["llama-3", "qwen", "gpt-4o"],
    strengths: [
      "Strong multilingual support",
      "Enterprise-friendly positioning",
      "Clean API",
    ],
    weaknesses: [
      "Closed flagship weights",
      "Ecosystem smaller than some larger platforms",
    ],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
  {
    id: "xai-grok",
    slug: "grok",
    name: "Grok",
    company: "xAI",
    accentColor: "#64748b",
    logo: "grok.svg",
    shortDescription:
      "Conversational model family with real-time social context in xAI products.",
    description:
      "Grok is a conversational model family from xAI, often associated with real-time information workflows and integration into X-based product experiences.",
    categories: ["text-generation", "research"],
    tags: ["chat", "real-time", "social context", "reasoning"],
    bestFor: [
      "Conversational search",
      "Social trend analysis",
      "General chat",
      "Current event exploration",
    ],
    modalities: ["text", "image", "reasoning"],
    pricing: {
      type: "freemium",
      startingPrice: "Subscription and usage tiers",
    },
    apiAvailable: true,
    openSource: false,
    localRunnable: false,
    contextWindow: 131000,
    releaseDate: "2023-11-04",
    website: "https://x.ai",
    documentation: "https://docs.x.ai",
    comparisons: ["gpt-4o", "gemini-2-5-pro"],
    strengths: [
      "Real-time product positioning",
      "Useful for trend-aware chat",
      "API availability",
    ],
    weaknesses: [
      "Closed weights",
      "Best experience may depend on xAI ecosystem access",
    ],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
  {
    id: "alibaba-qwen",
    slug: "qwen",
    name: "Qwen",
    company: "Alibaba Cloud",
    accentColor: "#7c3aed",
    logo: "qwen.svg",
    shortDescription:
      "Open and commercial model family with strong multilingual and coding coverage.",
    description:
      "Qwen is a broad model family with open-weight releases and hosted APIs, spanning chat, coding, math, vision, and multilingual applications.",
    categories: ["text-generation", "coding", "open-source"],
    tags: ["open weights", "multilingual", "coding", "math"],
    bestFor: [
      "Self-hosted chat",
      "Coding",
      "Multilingual products",
      "Fine-tuning",
    ],
    modalities: ["text", "image", "code", "reasoning"],
    pricing: { type: "freemium", startingPrice: "Varies by host" },
    apiAvailable: true,
    openSource: true,
    localRunnable: true,
    contextWindow: 128000,
    releaseDate: "2023-08-03",
    website: "https://qwenlm.github.io",
    documentation: "https://help.aliyun.com/zh/model-studio",
    featured: true,
    comparisons: ["llama-3", "mistral-large", "deepseek-r1"],
    strengths: [
      "Strong open ecosystem",
      "Good multilingual coverage",
      "Useful coding variants",
    ],
    weaknesses: [
      "Variant selection can be confusing",
      "Hosting quality varies",
    ],
    speed: "fast",
    lastUpdated: "2026-05-14",
  },
];

export const models: AIModel[] = [
  ...multimodalModels,
  ...audioGenerationModels,
  ...codingModels,
  ...videoGenerationModels,
  ...imageGenerationModels,
];
