import type { AIPlatform } from "@/types/platform";

export const platforms: AIPlatform[] = [
  {
    id: "chatgpt",
    slug: "chatgpt",
    name: "ChatGPT",
    company: "OpenAI",
    logo: "open-ai.svg",
    accentColor: "#10a37f",
    shortDescription:
      "OpenAI's flagship assistant platform for writing, coding, research, image understanding, and multimodal workflows.",
    description:
      "ChatGPT is a broad AI assistant platform for individuals and teams. It combines conversational AI, multimodal input, coding help, file analysis, image generation, and a mature API ecosystem for building AI products.",
    categories: ["text-generation", "coding", "research"],
    tags: ["assistant", "multimodal", "coding", "api", "agents"],
    bestFor: [
      "General AI assistance",
      "Writing",
      "Coding help",
      "Product assistants",
      "Research synthesis",
    ],
    pricing: {
      free: true,
      paid: true,
      notes: "Free and paid plans, plus API usage billing.",
    },
    apiAvailable: true,
    openSource: false,
    website: "https://chatgpt.com",
    documentation: "https://platform.openai.com/docs",
    strengths: [
      "Polished general-purpose UX",
      "Strong API ecosystem",
      "Broad multimodal support",
    ],
    weaknesses: ["Closed platform", "Advanced usage can become costly"],
    models: [
      {
        name: "GPT-4o",
        description:
          "Flagship multimodal model for text, vision, and voice workflows.",
      },
      {
        name: "GPT-4.1",
        description:
          "Model family oriented around strong instruction following and coding.",
      },
      {
        name: "o-series",
        description: "Reasoning-focused models for complex problem solving.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
  },
  {
    id: "claude",
    slug: "claude",
    name: "Claude",
    company: "Anthropic",
    logo: "claude.svg",
    accentColor: "#d97757",
    shortDescription:
      "Anthropic's assistant platform for careful writing, code review, long-context analysis, and agentic workflows.",
    description:
      "Claude is a premium AI assistant platform focused on high-quality reasoning, polished long-form output, strong coding assistance, and thoughtful document analysis for professional teams.",
    categories: ["text-generation", "coding", "research"],
    tags: ["assistant", "coding", "long context", "reasoning", "writing"],
    bestFor: [
      "Code review",
      "Long document analysis",
      "Research synthesis",
      "Complex writing",
    ],
    pricing: {
      free: true,
      paid: true,
      notes: "Free and paid app plans with API usage billing.",
    },
    apiAvailable: true,
    openSource: false,
    website: "https://claude.ai",
    documentation: "https://docs.anthropic.com",
    strengths: [
      "Excellent writing quality",
      "Strong code reasoning",
      "Large context workflows",
    ],
    weaknesses: ["Closed platform", "Some features vary by plan and region"],
    models: [
      {
        name: "Claude Sonnet",
        description:
          "Balanced model line for reasoning, coding, and everyday work.",
      },
      {
        name: "Claude Opus",
        description: "Higher-capability model line for demanding tasks.",
      },
      {
        name: "Claude Haiku",
        description: "Fast, lower-cost model line for lightweight workflows.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
  },
  {
    id: "gemini",
    slug: "gemini",
    name: "Gemini",
    company: "Google",
    logo: "gemini.svg",
    accentColor: "#4285f4",
    shortDescription:
      "Google's multimodal AI platform for search, Workspace, long-context analysis, and developer apps.",
    description:
      "Gemini brings Google's AI models into consumer, enterprise, and developer workflows. It is especially useful for long-context research, multimodal understanding, and Google ecosystem integrations.",
    categories: ["text-generation", "coding", "research"],
    tags: ["google", "multimodal", "long context", "workspace", "api"],
    bestFor: [
      "Research",
      "Workspace workflows",
      "Long document analysis",
      "Multimodal apps",
    ],
    pricing: {
      free: true,
      paid: true,
      notes:
        "Free and paid app plans with API billing through Google AI tooling.",
    },
    apiAvailable: true,
    openSource: false,
    website: "https://gemini.google.com",
    documentation: "https://ai.google.dev",
    strengths: [
      "Deep Google integration",
      "Very large-context workflows",
      "Strong multimodal support",
    ],
    weaknesses: [
      "Closed platform",
      "Capabilities can differ across Google products",
    ],
    models: [
      {
        name: "Gemini Pro",
        description:
          "Higher-capability model line for complex reasoning and analysis.",
      },
      {
        name: "Gemini Flash",
        description:
          "Fast model line for lightweight and cost-sensitive tasks.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
  },
  {
    id: "deepseek",
    slug: "deepseek",
    name: "DeepSeek",
    company: "DeepSeek",
    logo: "deepseek.svg",
    accentColor: "#4f46e5",
    shortDescription:
      "AI platform known for reasoning models, coding utility, open-weight releases, and cost-efficient APIs.",
    description:
      "DeepSeek is a developer-focused AI platform with reasoning, coding, and multimodal model work. It appeals to teams looking for strong reasoning value, open-weight options, and flexible deployment paths.",
    categories: [
      "text-generation",
      "coding",
      "research",
      "open-source",
      "image-generation",
    ],
    tags: ["reasoning", "coding", "open weights", "api", "multimodal"],
    bestFor: [
      "Reasoning tasks",
      "Coding experiments",
      "Self-hosted workflows",
      "Cost-sensitive APIs",
    ],
    pricing: {
      free: true,
      paid: true,
      notes: "Open weights for some models; hosted API pricing varies.",
    },
    apiAvailable: true,
    openSource: true,
    website: "https://www.deepseek.com",
    documentation: "https://api-docs.deepseek.com",
    strengths: [
      "Strong reasoning value",
      "Open-weight options",
      "Developer-friendly pricing",
    ],
    weaknesses: [
      "Operational quality depends on host",
      "Product polish varies by workflow",
    ],
    models: [
      { name: "DeepSeek R1", description: "Reasoning-focused model family." },
      {
        name: "DeepSeek V-series",
        description: "General-purpose chat and coding model line.",
      },
      {
        name: "Janus Pro",
        description:
          "Multimodal model line for image understanding and generation.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
  },
  {
    id: "cursor",
    slug: "cursor",
    name: "Cursor",
    company: "Anysphere",
    logo: "cursor.svg",
    accentColor: "#111827",
    shortDescription:
      "AI-native code editor for pair programming, repo-aware chat, refactors, and developer workflows.",
    description:
      "Cursor is a code editor built around practical AI assistance. It is useful for navigating codebases, editing files, generating implementations, reviewing code, and speeding up everyday engineering work.",
    categories: ["coding"],
    tags: ["code editor", "developer tools", "agent", "refactor", "repo chat"],
    bestFor: [
      "Codebase navigation",
      "Refactors",
      "Feature implementation",
      "Developer productivity",
    ],
    pricing: {
      free: true,
      paid: true,
      notes: "Free tier and paid subscriptions.",
    },
    apiAvailable: false,
    openSource: false,
    website: "https://cursor.com",
    strengths: [
      "Excellent editor workflow",
      "Repo-aware assistance",
      "Practical coding UX",
    ],
    weaknesses: [
      "Not a foundation model provider",
      "Best value depends on supported model choices",
    ],
    models: [
      {
        name: "Model picker",
        description:
          "Cursor can use multiple hosted model providers depending on plan and availability.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
  },
  {
    id: "perplexity",
    slug: "perplexity",
    name: "Perplexity",
    company: "Perplexity AI",
    logo: "perplexity.svg",
    accentColor: "#20b8bd",
    shortDescription:
      "Answer engine for research, web-grounded discovery, citations, and current information workflows.",
    description:
      "Perplexity is a research and answer platform built around web-grounded responses, source citations, and fast exploration. It is best used when users need to discover, verify, and summarize current information.",
    categories: ["research", "text-generation"],
    tags: ["search", "citations", "research", "web", "answers"],
    bestFor: [
      "Research",
      "Source-backed answers",
      "Market discovery",
      "Current event exploration",
    ],
    pricing: { free: true, paid: true, notes: "Free and paid plans." },
    apiAvailable: true,
    openSource: false,
    website: "https://www.perplexity.ai",
    documentation: "https://docs.perplexity.ai",
    strengths: [
      "Strong source-backed UX",
      "Fast web research",
      "Good for discovery workflows",
    ],
    weaknesses: [
      "Not ideal for all creative generation tasks",
      "Source quality still requires review",
    ],
    models: [
      {
        name: "Perplexity Sonar",
        description: "API-oriented model family for search-grounded answers.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
  },
  {
    id: "midjourney",
    slug: "midjourney",
    name: "Midjourney",
    company: "Midjourney",
    logo: "midjourney.svg",
    accentColor: "#8b5cf6",
    shortDescription:
      "Premium image generation platform for expressive visual exploration, art direction, and high-style concepts.",
    description:
      "Midjourney is a polished image generation platform favored by designers, artists, and creative teams that want striking visual output without managing model infrastructure.",
    categories: ["image-generation"],
    tags: ["image", "art direction", "design", "creative", "visuals"],
    bestFor: [
      "Art direction",
      "Moodboards",
      "Editorial visuals",
      "Creative exploration",
    ],
    pricing: { free: false, paid: true, notes: "Paid subscription." },
    apiAvailable: false,
    openSource: false,
    website: "https://www.midjourney.com",
    strengths: [
      "Distinctive visual quality",
      "Fast creative iteration",
      "Strong community workflows",
    ],
    weaknesses: ["No broadly available official API", "Closed platform"],
    models: [
      {
        name: "Midjourney",
        description: "Continuously updated image generation model family.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
  },
  {
    id: "runway",
    slug: "runway",
    name: "Runway",
    company: "Runway",
    logo: "runway.svg",
    accentColor: "#14b8a6",
    shortDescription:
      "Creative video platform for generation, editing, image-to-video workflows, and production teams.",
    description:
      "Runway combines AI video generation with a production-focused web editor. It is useful for teams moving from ideation to polished video concepts in one creative workflow.",
    categories: ["video-generation"],
    tags: ["video", "editor", "creative suite", "image-to-video", "production"],
    bestFor: [
      "Video ideation",
      "Production workflows",
      "Storyboards",
      "Creative teams",
    ],
    pricing: {
      free: true,
      paid: true,
      notes: "Free tier and paid credit/subscription plans.",
    },
    apiAvailable: true,
    openSource: false,
    website: "https://runwayml.com",
    documentation: "https://docs.dev.runwayml.com",
    strengths: [
      "Strong product workflow",
      "Editing tools included",
      "Team-friendly interface",
    ],
    weaknesses: [
      "Closed system",
      "Credit costs can matter for heavy iteration",
    ],
    models: [
      {
        name: "Gen series",
        description: "Runway's video generation model family.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
  },
  {
    id: "elevenlabs",
    slug: "elevenlabs",
    name: "ElevenLabs",
    company: "ElevenLabs",
    logo: "elevenlabs.svg",
    accentColor: "#6366f1",
    shortDescription:
      "Voice AI platform for speech synthesis, dubbing, narration, voice cloning, and agent audio.",
    description:
      "ElevenLabs provides voice generation, dubbing, voice cloning, and speech tools for creators and product teams that need natural spoken audio.",
    categories: ["audio"],
    tags: ["voice", "speech", "dubbing", "agents", "audio"],
    bestFor: ["Narration", "Voice agents", "Localization", "Creator audio"],
    pricing: {
      free: true,
      paid: true,
      notes: "Free tier and paid subscription/usage plans.",
    },
    apiAvailable: true,
    openSource: false,
    website: "https://elevenlabs.io",
    documentation: "https://elevenlabs.io/docs",
    strengths: [
      "Natural voice quality",
      "Strong API",
      "Broad creator and product use cases",
    ],
    weaknesses: [
      "Closed model",
      "Voice rights and consent need careful governance",
    ],
    models: [
      {
        name: "Eleven Multilingual",
        description: "Voice generation model family for multilingual speech.",
      },
      {
        name: "Dubbing and voice tools",
        description: "Specialized products for localization and production.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
  },
  {
    id: "suno",
    slug: "suno",
    name: "Suno",
    company: "Suno",
    logo: "suno.svg",
    accentColor: "#ec4899",
    shortDescription:
      "Music generation platform for creating songs, demos, lyrics, and rapid audio concepts.",
    description:
      "Suno helps creators generate complete songs and musical ideas from prompts. It is strongest for drafts, demos, creator content, and fast audio experimentation.",
    categories: ["music", "audio"],
    tags: ["music", "songs", "lyrics", "creator", "audio"],
    bestFor: [
      "Song ideas",
      "Demos",
      "Creator content",
      "Audio experimentation",
    ],
    pricing: {
      free: true,
      paid: true,
      notes: "Free tier and paid subscriptions.",
    },
    apiAvailable: false,
    openSource: false,
    website: "https://suno.com",
    strengths: [
      "Fast full-song generation",
      "Accessible creative UX",
      "Good for ideation",
    ],
    weaknesses: [
      "Limited production control compared with DAWs",
      "Closed platform",
    ],
    models: [
      {
        name: "Suno music model",
        description: "Platform model family for song and music generation.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
  },
  {
    id: "grok",
    slug: "grok",
    name: "Grok",
    company: "xAI",
    logo: "grok.svg",
    accentColor: "#64748b",
    shortDescription:
      "xAI's assistant platform for conversational AI, real-time social context, reasoning, and search-like workflows.",
    description:
      "Grok is a conversational AI platform from xAI. It is often used for trend-aware chat, current event exploration, and general assistant workflows connected to the xAI ecosystem.",
    categories: ["text-generation", "research"],
    tags: ["chat", "real-time", "social context", "reasoning"],
    bestFor: [
      "Conversational search",
      "Social trend analysis",
      "General chat",
      "Current event exploration",
    ],
    pricing: {
      free: true,
      paid: true,
      notes: "Availability and plan details vary by xAI product.",
    },
    apiAvailable: true,
    openSource: false,
    website: "https://x.ai",
    documentation: "https://docs.x.ai",
    strengths: [
      "Real-time product positioning",
      "Useful for trend-aware chat",
      "API availability",
    ],
    weaknesses: [
      "Closed platform",
      "Best experience may depend on xAI ecosystem access",
    ],
    models: [
      {
        name: "Grok model family",
        description: "xAI's conversational and reasoning model family.",
      },
    ],
    featured: true,
    lastUpdated: "2026-05-14",
  },
  {
    id: "mistral",
    slug: "mistral",
    name: "Mistral",
    company: "Mistral AI",
    logo: "mistral.svg",
    accentColor: "#ff7000",
    shortDescription:
      "European AI platform with open and commercial models for assistants, enterprise apps, and multilingual workflows.",
    description:
      "Mistral offers hosted APIs, enterprise AI products, and open model releases. It is a strong fit for multilingual assistants, European deployments, and teams that want flexible model options.",
    categories: ["text-generation", "coding", "open-source"],
    tags: ["multilingual", "enterprise", "api", "open models", "europe"],
    bestFor: [
      "Enterprise assistants",
      "Multilingual workflows",
      "EU-focused deployments",
      "Coding support",
    ],
    pricing: {
      free: true,
      paid: true,
      notes: "Open models and paid hosted API options.",
    },
    apiAvailable: true,
    openSource: true,
    website: "https://mistral.ai",
    documentation: "https://docs.mistral.ai",
    strengths: [
      "Strong multilingual support",
      "Enterprise-friendly positioning",
      "Open and commercial options",
    ],
    weaknesses: [
      "Ecosystem is smaller than some larger platforms",
      "Model selection can require evaluation",
    ],
    models: [
      {
        name: "Mistral Large",
        description: "Commercial model line for advanced assistant workflows.",
      },
      {
        name: "Mixtral",
        description: "Open model family used for flexible deployments.",
      },
    ],
    featured: true,
    lastUpdated: "2026-05-14",
  },
  {
    id: "qwen",
    slug: "qwen",
    name: "Qwen",
    company: "Alibaba Cloud",
    logo: "qwen.svg",
    accentColor: "#7c3aed",
    shortDescription:
      "Broad AI platform and model family with open releases, multilingual coverage, coding, math, and vision capabilities.",
    description:
      "Qwen spans open model releases and hosted Alibaba Cloud tooling. It is useful for self-hosted chat, coding, multilingual products, and teams that want flexible deployment paths.",
    categories: ["text-generation", "coding", "open-source"],
    tags: ["open models", "multilingual", "coding", "math", "vision"],
    bestFor: [
      "Self-hosted chat",
      "Coding",
      "Multilingual products",
      "Fine-tuning",
    ],
    pricing: {
      free: true,
      paid: true,
      notes: "Open models and hosted cloud usage options.",
    },
    apiAvailable: true,
    openSource: true,
    website: "https://qwenlm.github.io",
    documentation: "https://help.aliyun.com/zh/model-studio",
    strengths: [
      "Strong open ecosystem",
      "Good multilingual coverage",
      "Useful coding variants",
    ],
    weaknesses: [
      "Variant selection can be confusing",
      "Hosting quality varies",
    ],
    models: [
      {
        name: "Qwen",
        description:
          "General model family for chat, coding, math, and multimodal tasks.",
      },
      { name: "Qwen Coder", description: "Coding-oriented model variants." },
    ],
    featured: true,
    lastUpdated: "2026-05-14",
  },
  {
    id: "minimax",
    slug: "minimax",
    name: "MiniMax",
    company: "MiniMax",
    logo: "minimax.svg",
    accentColor: "#FF6B35",
    shortDescription:
      "Multimodal AI platform with text, vision, audio, and video generation models, known for competitive pricing and strong video capabilities via Hailuo AI.",
    description:
      "MiniMax offers a comprehensive AI platform spanning text generation, code, vision, and video (via Hailuo). Their models provide excellent cost-performance ratios, with both hosted API and open-source options. Ideal for teams needing multimodal capabilities, video generation, or cost-effective text processing.",
    categories: [
      "text-generation",
      "video-generation",
      "coding",
      "open-source",
    ],
    tags: ["multimodal", "video", "audio", "coding", "agent", "long-context"],
    bestFor: [
      "Video generation",
      "Multimodal products",
      "Cost-effective text processing",
      "Agentic workflows",
    ],
    pricing: {
      free: true,
      paid: true,
      notes:
        "Token Plans from \$10/month, pay-as-you-go from \$0.15/1M input tokens, video packages starting at \$1,000.",
    },
    apiAvailable: true,
    openSource: true,
    website: "https://www.minimax.io",
    documentation: "https://platform.minimax.io/docs",
    strengths: [
      "Excellent video generation via Hailuo",
      "Competitive pricing",
      "Strong multimodal capabilities",
      "Ultra-long context support",
    ],
    weaknesses: [
      "Less brand recognition in Western markets",
      "Documentation could be more comprehensive",
    ],
    models: [
      {
        name: "MiniMax-M2.7",
        description:
          "Next-gen model for autonomous, real-world productivity and continuous improvement.",
      },
      {
        name: "MiniMax-Text-01",
        description:
          "Open-source large language model with strong reasoning capabilities.",
      },
      {
        name: "MiniMax-VL-01",
        description:
          "Vision-language model for multimodal understanding and generation.",
      },
      {
        name: "Hailuo AI",
        description:
          "Text-to-video generation with high-quality output and fast processing.",
      },
      {
        name: "T2A-01-HD",
        description: "High-definition text-to-audio synthesis model.",
      },
    ],
    featured: true,
    lastUpdated: "2026-05-14",
  },
  {
    id: "kimi",
    slug: "kimi",
    name: "Kimi",
    company: "Moonshot AI",
    logo: "kimi.svg",
    accentColor: "#2563EB",
    shortDescription:
      "AI assistant by Moonshot AI featuring industry-leading long-context windows, Mixture-of-Experts architecture, and advanced reasoning capabilities.",
    description:
      "Kimi is a family of large language models developed by Moonshot AI, built on a Mixture-of-Experts (MoE) architecture. It is renowned for ultra-long context support (up to 2 million characters), strong reasoning and coding abilities via Kimi K1.5, and autonomous agentic execution. Kimi powers both a popular consumer chat application and enterprise APIs, with particular strength in long-document analysis, multimodal understanding, and complex problem-solving.",
    categories: ["text-generation", "coding", "research", "open-source"],
    tags: [
      "long-context",
      "reasoning",
      "multimodal",
      "agent",
      "moe",
      "chinese",
    ],
    bestFor: [
      "Long document analysis",
      "Research",
      "Coding",
      "Multimodal understanding",
      "Agentic workflows",
    ],
    pricing: {
      free: true,
      paid: true,
      notes:
        "Free tier available for the chat app; API offered on a pay-as-you-go basis with competitive token rates.",
    },
    apiAvailable: true,
    openSource: true,
    website: "https://www.moonshot.ai",
    documentation: "https://platform.moonshot.cn",
    strengths: [
      "Industry-leading context length (up to 2 million characters)",
      "Strong reasoning and mathematical abilities via Kimi K1.5",
      "Efficient Mixture-of-Experts architecture",
      "Advanced autonomous agent capabilities",
      "Excellent Chinese language understanding",
    ],
    weaknesses: [
      "English generation can lag behind top Western models in nuance",
      "Availability restricted in certain regions",
      "API documentation and resources primarily in Chinese",
    ],
    models: [
      {
        name: "Kimi K1.5",
        description:
          "Reasoning-focused model optimized for complex problem solving, mathematics, and coding.",
      },
      {
        name: "Kimi",
        description:
          "Flagship conversational model supporting ultra-long contexts and general-purpose tasks.",
      },
      {
        name: "Kimi-VL",
        description:
          "Vision-language model for image understanding, OCR, and multimodal dialogue.",
      },
      {
        name: "Kimi-Moonlight",
        description:
          "Lightweight MoE model designed for efficient on-device and enterprise deployment.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
  },
  {
    id: "leonardo-ai",
    slug: "leonardo-ai",
    name: "Leonardo AI",
    company: "Leonardo AI (Canva)",
    logo: "leonardo-ai.svg",
    accentColor: "#9333EA",
    shortDescription:
      "Generative AI platform specializing in photorealistic image generation, game asset creation, 3D texture mapping, and marketing design workflows.",
    description:
      "Leonardo AI is a creative generative AI platform built for artists, game developers, and marketers. It offers industry-focused tools for photorealistic and stylized image generation, 3D texture synthesis, and video animation. Acquired by Canva, it bridges rapid asset prototyping with professional design workflows, featuring a vibrant community marketplace and robust API for production pipelines.",
    categories: ["image-generation", "video-generation"],
    tags: [
      "image-generation",
      "game-dev",
      "3d-textures",
      "design",
      "marketing",
      "asset-pipeline",
      "canva",
    ],
    bestFor: [
      "Game asset creation",
      "3D texture generation",
      "Marketing imagery",
      "Brand design",
      "Rapid creative prototyping",
    ],
    pricing: {
      free: true,
      paid: true,
      notes:
        "Free tier with daily credits; paid plans from ~$12/month. API access is usage-based.",
    },
    apiAvailable: true,
    openSource: false,
    website: "https://leonardo.ai",
    documentation: "https://docs.leonardo.ai",
    strengths: [
      "Industry-leading game asset and texture pipelines",
      "Strong style consistency and custom model training",
      "Tight integration with the Canva design ecosystem",
      "User-friendly interface for non-technical creatives",
      "Active community and asset marketplace",
    ],
    weaknesses: [
      "Primarily focused on image/video; lacks text/code capabilities",
      "Not open-source",
      "Credit system can be limiting for heavy production use",
      "Less suited for long-form or document-based tasks",
    ],
    models: [
      {
        name: "Leonardo Phoenix",
        description:
          "Flagship image generation model with high fidelity, prompt adherence, and artistic control.",
      },
      {
        name: "Leonardo Motion",
        description:
          "Video and animation generation from still images for dynamic content creation.",
      },
      {
        name: "Real-time Canvas",
        description:
          "Live drawing-to-image generation for iterative creative design.",
      },
      {
        name: "3D Texture Generation",
        description:
          "Generative texture synthesis designed for 3D meshes and game development pipelines.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
  },
  {
    id: "flux-1-1-pro",
    slug: "flux-1-1-pro",
    name: "FLUX.1.1 Pro",
    company: "Black Forest Labs",
    logo: "flux.svg",
    accentColor: "#000000",
    shortDescription:
      "State-of-the-art production-grade text-to-image model with exceptional prompt fidelity, photorealism, and speed.",
    description:
      "FLUX.1.1 Pro from Black Forest Labs delivers top-tier image quality with outstanding prompt adherence, visual accuracy, typography, and complex scene composition. Available via multiple inference providers.",
    categories: ["image-generation"],
    tags: [
      "flux",
      "photorealism",
      "prompt-adherence",
      "fast-inference",
      "typography",
    ],
    bestFor: [
      "Professional visuals",
      "Commercial use",
      "Complex scenes",
      "High-fidelity generation",
    ],
    pricing: {
      free: false,
      paid: true,
      notes:
        "Usage-based API pricing across providers (Replicate, fal.ai, BFL, etc.)",
    },
    apiAvailable: true,
    openSource: false,
    website: "https://playground.bfl.ai/image/generate",
    documentation: "https://docs.bfl.ai",
    strengths: [
      "Outstanding prompt fidelity",
      "High photorealism and detail",
      "Fast inference",
      "Excellent typography",
    ],
    weaknesses: [
      "Proprietary closed weights",
      "Cost accumulates with heavy usage",
    ],
    models: [
      {
        name: "FLUX.1.1 Pro",
        description:
          "Flagship production model optimized for quality and speed.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
    metadata: {
      release_date: "2025",
      architecture: "Rectified Flow Transformer",
      modality: "text-to-image",
      open_source: false,
      supported_resolutions: "Up to 4MP+",
      inference_speed: "Very fast (4-10 seconds)",
      licensing: "Proprietary",
      fine_tuning_support: null,
      lora_support: false,
      controlnet_ipadapter_support: true,
      img2img_support: true,
      inpainting_support: true,
      style_specialization: "General-purpose with strong realism",
      realism_capability: "Excellent",
      anime_design_capability: "Strong",
      benchmark_notes: "Leads or near top in human preference evaluations",
      huggingface_link: null,
      github_repo: "https://github.com/black-forest-labs/flux",
      research_paper: null,
    },
  },
  {
    id: "stable-diffusion-3-5-large",
    slug: "stable-diffusion-3-5-large",
    name: "Stable Diffusion 3.5 Large",
    company: "Stability AI",
    logo: "stability.svg",
    accentColor: "#000000",
    shortDescription:
      "Powerful open-weight text-to-image model with massive customization ecosystem.",
    description:
      "SD 3.5 Large offers improved prompt understanding, typography, and quality across Large, Turbo, and Medium variants, making it highly suitable for local and fine-tuned deployments.",
    categories: ["image-generation"],
    tags: ["stable-diffusion", "open-source", "customizable", "ecosystem"],
    bestFor: [
      "Local deployment",
      "Fine-tuning",
      "Creative experimentation",
      "Community workflows",
    ],
    pricing: {
      free: true,
      paid: false,
      notes: "Fully open weights; optional hosted services",
    },
    apiAvailable: true,
    openSource: true,
    website: "https://stability.ai",
    documentation: "https://stability.ai",
    strengths: [
      "Huge ecosystem of LoRAs and tools",
      "Fully customizable",
      "Local execution possible",
      "Strong community support",
    ],
    weaknesses: ["Requires hardware/setup", "Base quality varies by fine-tune"],
    models: [
      {
        name: "Stable Diffusion 3.5 Large",
        description: "Primary high-capability open model.",
      },
      {
        name: "Stable Diffusion 3.5 Large Turbo",
        description: "Distilled fast variant for speed.",
      },
    ],
    featured: true,
    trending: false,
    lastUpdated: "2026-05-14",
    metadata: {
      release_date: "2025",
      architecture: "MMDiT",
      modality: "text-to-image",
      open_source: true,
      supported_resolutions: "Up to 2048x2048+",
      inference_speed: "Varies by variant (Turbo: very fast)",
      licensing: "Open (permissive)",
      fine_tuning_support: true,
      lora_support: true,
      controlnet_ipadapter_support: true,
      img2img_support: true,
      inpainting_support: true,
      style_specialization: "Highly versatile via community",
      realism_capability: "Strong",
      anime_design_capability: "Excellent",
      benchmark_notes: "Top open-source performer",
      huggingface_link:
        "https://huggingface.co/stabilityai/stable-diffusion-3.5-large",
      github_repo: null,
      research_paper: null,
    },
  },
  {
    id: "ideogram-v3",
    slug: "ideogram-v3",
    name: "Ideogram V3",
    company: "Ideogram",
    logo: "ideogram.svg",
    accentColor: "#000000",
    shortDescription:
      "Leading model for photorealism and exceptional text rendering in design work.",
    description:
      "Ideogram V3 excels at accurate typography, strong prompt following, and production-ready design assets.",
    categories: ["image-generation"],
    tags: ["typography", "design", "text-rendering", "commercial"],
    bestFor: [
      "Posters",
      "Branding",
      "Text-heavy visuals",
      "Professional design",
    ],
    pricing: {
      free: true,
      paid: true,
      notes: "Free tier with limits + paid plans",
    },
    apiAvailable: true,
    openSource: false,
    website: "https://ideogram.ai",
    documentation: "https://ideogram.ai/docs",
    strengths: [
      "Best-in-class text rendering",
      "Strong photorealism",
      "Style consistency",
      "Design-oriented",
    ],
    weaknesses: ["Closed model", "Free tier limitations"],
    models: [
      {
        name: "Ideogram V3",
        description: "Flagship model with Turbo, Default, and Quality modes.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
    metadata: {
      release_date: "2025/2026",
      architecture: null,
      modality: "text-to-image",
      open_source: false,
      supported_resolutions: "1024x1024 and variants",
      inference_speed: "Fast",
      licensing: "Proprietary",
      fine_tuning_support: null,
      lora_support: null,
      controlnet_ipadapter_support: null,
      img2img_support: true,
      inpainting_support: true,
      style_specialization: "Typography and design",
      realism_capability: "Excellent",
      anime_design_capability: "Good",
      benchmark_notes: "Top in text-in-image benchmarks",
      huggingface_link: null,
      github_repo: null,
      research_paper: null,
    },
  },
  {
    id: "imagen-4",
    slug: "imagen-4",
    name: "Imagen 4",
    company: "Google DeepMind",
    logo: "deepmind.svg",
    accentColor: "#4285f4",
    shortDescription:
      "Google's flagship photorealistic text-to-image model with excellent detail and integration.",
    description:
      "Imagen 4 (including Ultra and Fast variants) produces high-clarity photorealistic images with strong composition.",
    categories: ["image-generation"],
    tags: ["google", "photorealism", "clarity"],
    bestFor: ["Photorealistic scenes", "High-detail work", "Google ecosystem"],
    pricing: {
      free: false,
      paid: true,
      notes: "Via Google AI Studio / Vertex AI",
    },
    apiAvailable: true,
    openSource: false,
    website: "https://deepmind.google/models/imagen/",
    documentation: "https://ai.google.dev",
    strengths: [
      "High photorealism",
      "Sharp detail and lighting",
      "Strong composition",
      "Fast variants",
    ],
    weaknesses: ["Closed platform", "Availability restrictions"],
    models: [
      {
        name: "Imagen 4 Ultra",
        description: "Highest quality variant for maximum fidelity.",
      },
      {
        name: "Imagen 4 Fast",
        description: "Speed-optimized variant.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
    metadata: {
      release_date: "2025/2026",
      architecture: null,
      modality: "text-to-image",
      open_source: false,
      supported_resolutions: "Up to 2K+",
      inference_speed: "Fast to moderate",
      licensing: "Proprietary",
      fine_tuning_support: null,
      lora_support: null,
      controlnet_ipadapter_support: null,
      img2img_support: true,
      inpainting_support: true,
      style_specialization: "Photorealism",
      realism_capability: "State-of-the-art",
      anime_design_capability: "Good",
      benchmark_notes: "Top-tier in human evaluations",
      huggingface_link: null,
      github_repo: null,
      research_paper: null,
    },
  },
  {
    id: "hunyuanimage-3-0",
    slug: "hunyuanimage-3-0",
    name: "HunyuanImage 3.0",
    company: "Tencent",
    logo: "hunyuan.svg",
    accentColor: "#000000",
    shortDescription:
      "Large-scale open multimodal autoregressive image generation model.",
    description:
      "80B+ parameter MoE model with native multimodal capabilities and strong performance in complex scenes and multilingual text.",
    categories: ["image-generation"],
    tags: ["open-source", "moe", "multimodal", "large-scale"],
    bestFor: ["High-quality open deployments", "Research", "Complex scenes"],
    pricing: {
      free: true,
      paid: true,
      notes: "Open weights available; hosted options",
    },
    apiAvailable: true,
    openSource: true,
    website: "https://aistudio.tencent.com/",
    documentation: "https://github.com/Tencent-Hunyuan/HunyuanImage-3.0",
    strengths: [
      "Massive scale",
      "Strong multimodal integration",
      "Excellent text rendering",
      "High visual quality",
    ],
    weaknesses: [
      "High compute requirements",
      "Stronger Chinese ecosystem focus",
    ],
    models: [
      {
        name: "HunyuanImage 3.0",
        description: "Native multimodal autoregressive flagship model.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
    metadata: {
      release_date: "2025",
      architecture: "Autoregressive MoE",
      modality: "text-to-image, multimodal",
      open_source: true,
      supported_resolutions: "High resolutions",
      inference_speed: "Moderate to high resource",
      licensing: "Open weights",
      fine_tuning_support: true,
      lora_support: true,
      controlnet_ipadapter_support: true,
      img2img_support: true,
      inpainting_support: true,
      style_specialization: "General + multilingual",
      realism_capability: "Excellent",
      anime_design_capability: "Strong",
      benchmark_notes: "Competitive with closed leaders",
      huggingface_link: "https://huggingface.co/tencent/HunyuanImage-3.0",
      github_repo: "https://github.com/Tencent-Hunyuan/HunyuanImage-3.0",
      research_paper: "https://arxiv.org/pdf/2509.23951",
    },
  },
  {
    id: "recraft-v4",
    slug: "recraft-v4",
    name: "Recraft V4",
    company: "Recraft",
    logo: "recraft.svg",
    accentColor: "#000000",
    shortDescription:
      "Design-forward model optimized for professional creative and marketing assets.",
    description:
      "Recraft V4 emphasizes visual taste, balanced composition, and production-ready outputs with vector and raster support.",
    categories: ["image-generation"],
    tags: ["design", "vector", "professional", "marketing"],
    bestFor: ["Marketing assets", "UI/UX", "Branding", "Vector work"],
    pricing: {
      free: true,
      paid: true,
      notes: "Platform subscription",
    },
    apiAvailable: true,
    openSource: false,
    website: "https://recraft.ai",
    documentation: "https://www.recraft.ai/docs",
    strengths: [
      "Strong design aesthetics",
      "Vector generation support",
      "Professional polish",
      "Brand consistency",
    ],
    weaknesses: ["Less suited for pure artistic exploration", "Closed model"],
    models: [
      {
        name: "Recraft V4",
        description: "Current flagship vector and raster model.",
      },
      {
        name: "Recraft V4 Pro",
        description: "Higher quality variant.",
      },
    ],
    featured: true,
    trending: false,
    lastUpdated: "2026-05-14",
    metadata: {
      release_date: "February 2026",
      architecture: null,
      modality: "text-to-image",
      open_source: false,
      supported_resolutions: "1024x1024+",
      inference_speed: "Fast",
      licensing: "Proprietary",
      fine_tuning_support: null,
      lora_support: null,
      controlnet_ipadapter_support: null,
      img2img_support: true,
      inpainting_support: true,
      style_specialization: "Design and vector",
      realism_capability: "Strong",
      anime_design_capability: "Good",
      benchmark_notes: "Highly regarded for professional use",
      huggingface_link: null,
      github_repo: null,
      research_paper: null,
    },
  },
  {
    id: "grok-imagine",
    slug: "grok-imagine",
    name: "Grok Imagine",
    company: "xAI",
    logo: "grok.svg",
    accentColor: "#64748b",
    shortDescription:
      "xAI's creative image generation model integrated with Grok reasoning.",
    description:
      "Grok Imagine delivers high-quality image generation with strong creative and cinematic capabilities.",
    categories: ["image-generation"],
    tags: ["xai", "creative", "multimodal"],
    bestFor: ["Creative ideation", "Trend-aware images", "Cinematic outputs"],
    pricing: {
      free: true,
      paid: true,
      notes: "Tied to xAI/Grok subscription plans",
    },
    apiAvailable: true,
    openSource: false,
    website: "https://grok.com/imagine",
    documentation: "https://docs.x.ai",
    strengths: [
      "Creative and cinematic style",
      "Integration with Grok reasoning",
      "Fast generation",
    ],
    weaknesses: ["Ecosystem dependent", "Newer in dedicated image generation"],
    models: [
      {
        name: "Grok Imagine",
        description: "Flagship image generation model from xAI.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
    metadata: {
      release_date: "2025/2026",
      architecture: null,
      modality: "text-to-image",
      open_source: false,
      supported_resolutions: "1K & 2K",
      inference_speed: "Fast",
      licensing: "Proprietary",
      fine_tuning_support: null,
      lora_support: null,
      controlnet_ipadapter_support: null,
      img2img_support: true,
      inpainting_support: true,
      style_specialization: "Cinematic and creative",
      realism_capability: "Strong",
      anime_design_capability: "Good",
      benchmark_notes: "Competitive in creative benchmarks",
      huggingface_link: null,
      github_repo: null,
      research_paper: null,
    },
  },
  {
    id: "kling-3-0",
    slug: "kling-3-0",
    name: "Kling 3.0",
    company: "Kuaishou",
    logo: "kling.svg",
    accentColor: "#FF0000",
    shortDescription:
      "High-motion text-to-video and image-to-video model known for excellent character consistency, long clips, and strong physics.",
    description:
      "Kling 3.0 from Kuaishou is one of the top commercial video generation models in 2026. It excels at realistic human motion, long-duration clips (up to 2+ minutes), native audio support, and high prompt adherence for dynamic scenes.",
    categories: ["video-generation"],
    tags: [
      "text-to-video",
      "image-to-video",
      "character-consistency",
      "long-clip",
      "audio",
    ],
    bestFor: [
      "Character-driven videos",
      "Marketing & social content",
      "Long-form scenes",
      "High-motion sequences",
    ],
    pricing: {
      free: true,
      paid: true,
      notes:
        "Generous free daily credits + paid plans with usage-based pricing",
    },
    apiAvailable: true,
    openSource: false,
    website: "https://klingai.com",
    documentation: "https://klingai.com/docs",
    strengths: [
      "Excellent character and face consistency",
      "Strong motion realism and physics",
      "Long video support",
      "Native audio & lip-sync",
    ],
    weaknesses: [
      "Occasional artifacts in complex scenes",
      "Regional access variations",
    ],
    models: [
      {
        name: "Kling 3.0",
        description:
          "Flagship model with Standard and Pro modes for quality vs speed.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
    metadata: {
      release_date: "Early 2026",
      architecture: "Diffusion Transformer",
      modality: "text-to-video, image-to-video",
      open_source: false,
      supported_resolutions: "1080p (up to 4K upscaling)",
      inference_speed: "Moderate to fast",
      licensing: "Proprietary",
      fine_tuning_support: null,
      lora_support: null,
      controlnet_ipadapter_support: true,
      img2img_support: true,
      inpainting_support: true,
      style_specialization: "Realistic human motion and cinematic",
      realism_capability: "Excellent",
      anime_design_capability: "Strong",
      benchmark_notes: "Top-tier in motion quality and consistency",
      huggingface_link: null,
      github_repo: null,
      research_paper: null,
    },
  },
  {
    id: "luma-ray3",
    slug: "luma-ray3",
    name: "Luma Ray 3",
    company: "Luma AI",
    logo: "luma.svg",
    accentColor: "#00BFFF",
    shortDescription:
      "Advanced video generation model focused on physically accurate motion, atmospheric effects, and high-quality image-to-video.",
    description:
      "Luma Ray 3 (successor to Dream Machine) excels at natural physics, fluid dynamics, lighting, and cinematic camera movements. Particularly strong for surreal and atmospheric video generation.",
    categories: ["video-generation"],
    tags: [
      "image-to-video",
      "physics-simulation",
      "cinematic",
      "dream-machine",
    ],
    bestFor: [
      "Cinematic and artistic videos",
      "Surreal atmospheres",
      "High-fidelity image-to-video",
      "Creative storytelling",
    ],
    pricing: {
      free: true,
      paid: true,
      notes: "Free tier + paid subscription/credit plans",
    },
    apiAvailable: true,
    openSource: false,
    website: "https://lumalabs.ai",
    documentation: "https://lumalabs.ai/docs",
    strengths: [
      "Superior physics and natural motion",
      "Excellent lighting and atmosphere",
      "Strong image-to-video coherence",
      "Cinematic quality",
    ],
    weaknesses: [
      "Shorter clip lengths compared to competitors",
      "Higher cost for heavy usage",
    ],
    models: [
      {
        name: "Ray 3",
        description: "Latest flagship video generation model.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
    metadata: {
      release_date: "2026",
      architecture: "Diffusion-based",
      modality: "text-to-video, image-to-video",
      open_source: false,
      supported_resolutions: "1080p (HDR support)",
      inference_speed: "Moderate",
      licensing: "Proprietary",
      fine_tuning_support: null,
      lora_support: null,
      controlnet_ipadapter_support: true,
      img2img_support: true,
      inpainting_support: true,
      style_specialization: "Cinematic and atmospheric",
      realism_capability: "Excellent",
      anime_design_capability: "Good",
      benchmark_notes: "Leads in physical simulation and visual fidelity",
      huggingface_link: null,
      github_repo: null,
      research_paper: null,
    },
  },
  {
    id: "veo-3-1",
    slug: "veo-3-1",
    name: "Veo 3.1",
    company: "Google DeepMind",
    logo: "deepmind.svg",
    accentColor: "#4285f4",
    shortDescription:
      "Google's flagship video generation model with native audio, high realism, and strong narrative understanding.",
    description:
      "Veo 3.1 delivers top-tier cinematic quality with native synchronized audio, excellent prompt following, and character consistency. Deeply integrated with Google tools.",
    categories: ["video-generation"],
    tags: ["native-audio", "cinematic", "google", "high-fidelity"],
    bestFor: [
      "Marketing videos",
      "Narrative storytelling",
      "Professional production",
      "Audio-synced content",
    ],
    pricing: {
      free: false,
      paid: true,
      notes: "Available via Google AI Studio / Vertex AI",
    },
    apiAvailable: true,
    openSource: false,
    website: "https://deepmind.google/models/veo/",
    documentation: "https://ai.google.dev",
    strengths: [
      "Native audio generation & lip-sync",
      "High cinematic realism",
      "Strong narrative coherence",
      "4K output support",
    ],
    weaknesses: ["Closed platform with access limits", "Higher pricing tier"],
    models: [
      {
        name: "Veo 3.1",
        description: "Flagship model with Quality and Fast variants.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
    metadata: {
      release_date: "2026",
      architecture: null,
      modality: "text-to-video, image-to-video",
      open_source: false,
      supported_resolutions: "Up to 4K",
      inference_speed: "Fast variants available",
      licensing: "Proprietary",
      fine_tuning_support: null,
      lora_support: null,
      controlnet_ipadapter_support: null,
      img2img_support: true,
      inpainting_support: true,
      style_specialization: "Cinematic realism",
      realism_capability: "State-of-the-art",
      anime_design_capability: "Strong",
      benchmark_notes: "Frequently ranked #1 or #2 overall",
      huggingface_link: null,
      github_repo: null,
      research_paper: null,
    },
  },
  {
    id: "sora-2",
    slug: "sora-2",
    name: "Sora 2",
    company: "OpenAI",
    logo: "sora.svg",
    accentColor: "#10a37f",
    shortDescription:
      "OpenAI's advanced video generation model focused on cinematic realism, world simulation, and narrative coherence.",
    description:
      "Sora 2 continues OpenAI's leadership in world simulation with impressive physics, character consistency, and storytelling capabilities.",
    categories: ["video-generation"],
    tags: ["cinematic", "world-simulation", "narrative"],
    bestFor: [
      "Cinematic storytelling",
      "Film-like clips",
      "Complex scene simulation",
    ],
    pricing: {
      free: false,
      paid: true,
      notes: "Available via ChatGPT Plus/Pro or API",
    },
    apiAvailable: true,
    openSource: false,
    website: "https://openai.com/sora",
    documentation: "https://platform.openai.com/docs",
    strengths: [
      "Exceptional world physics",
      "Strong narrative understanding",
      "Cinematic quality",
      "High realism",
    ],
    weaknesses: [
      "Limited public availability",
      "Higher cost",
      "Shorter clips in base version",
    ],
    models: [
      {
        name: "Sora 2",
        description: "Flagship video generation model.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
    metadata: {
      release_date: "2025/2026",
      architecture: "Diffusion Transformer",
      modality: "text-to-video",
      open_source: false,
      supported_resolutions: "1080p+",
      inference_speed: "Moderate",
      licensing: "Proprietary",
      fine_tuning_support: null,
      lora_support: null,
      controlnet_ipadapter_support: null,
      img2img_support: true,
      inpainting_support: true,
      style_specialization: "Cinematic and realistic",
      realism_capability: "Excellent",
      anime_design_capability: "Good",
      benchmark_notes: "Top performer in world simulation",
      huggingface_link: null,
      github_repo: null,
      research_paper: null,
    },
  },
  {
    id: "cogvideox-5b",
    slug: "cogvideox-5b",
    name: "CogVideoX-5B",
    company: "THUDM / Zhipu AI",
    logo: "cogvideo.svg",
    accentColor: "#000000",
    shortDescription:
      "Strong open-source video generation model with good prompt adherence and accessible hardware requirements.",
    description:
      "CogVideoX-5B is a leading open-source text-to-video and image-to-video model. It offers a practical balance of quality and efficiency for local or self-hosted deployments.",
    categories: ["video-generation"],
    tags: ["open-source", "text-to-video", "image-to-video"],
    bestFor: [
      "Local/self-hosted video gen",
      "Research and experimentation",
      "Custom workflows",
    ],
    pricing: {
      free: true,
      paid: false,
      notes: "Fully open weights",
    },
    apiAvailable: true,
    openSource: true,
    website: "https://storyteller.ai/",
    documentation: "https://github.com/THUDM/CogVideo/blob/main/README.md",
    strengths: [
      "Fully open-source and runnable locally",
      "Good prompt understanding",
      "Reasonable hardware requirements",
      "Active community support",
    ],
    weaknesses: [
      "Lower quality than top closed models",
      "Shorter clip lengths",
      "Requires technical setup",
    ],
    models: [
      {
        name: "CogVideoX-5B",
        description: "Primary 5B parameter open video generation model.",
      },
      {
        name: "CogVideoX-2B",
        description: "Lightweight variant for lower hardware.",
      },
    ],
    featured: true,
    trending: false,
    lastUpdated: "2026-05-14",
    metadata: {
      release_date: "2025",
      architecture: "Diffusion",
      modality: "text-to-video, image-to-video",
      open_source: true,
      supported_resolutions: "720p-1080p",
      inference_speed: "Depends on hardware",
      licensing: "Open (permissive)",
      fine_tuning_support: true,
      lora_support: true,
      controlnet_ipadapter_support: true,
      img2img_support: true,
      inpainting_support: true,
      style_specialization: "General purpose",
      realism_capability: "Good",
      anime_design_capability: "Strong",
      benchmark_notes: "Leading open-source performer",
      huggingface_link: "https://huggingface.co/THUDM/CogVideoX-5b",
      github_repo: "https://github.com/THUDM/CogVideo",
      research_paper: null,
    },
  },
  {
    id: "manus-ai",
    slug: "manus-ai",
    name: "Manus AI",
    company: "Monica",
    logo: "manus.svg",
    accentColor: "#4f46e5",
    shortDescription:
      "Autonomous AI agent platform focused on executing complex tasks, research workflows, and multi-step automation.",
    description:
      "Manus AI is an autonomous AI agent platform designed to independently plan, execute, and complete complex digital tasks. It combines reasoning, browsing, research, coding, and workflow orchestration into a persistent agent experience aimed at productivity, operations, and deep task automation.",
    categories: ["research", "coding", "text-generation"],
    tags: [
      "agents",
      "automation",
      "research",
      "workflow",
      "autonomous-ai",
      "productivity",
    ],
    bestFor: [
      "Autonomous task execution",
      "Research workflows",
      "Business automation",
      "Multi-step planning",
      "AI operations assistants",
    ],
    pricing: {
      free: false,
      paid: true,
      notes:
        "Primarily waitlist and paid-access based during early platform rollout.",
    },
    apiAvailable: false,
    openSource: false,
    website: "https://manus.im",
    documentation: "https://manus.im",
    strengths: [
      "Strong autonomous workflow execution",
      "Handles long-running multi-step tasks",
      "Integrated browsing and reasoning capabilities",
      "Agent-oriented UX for productivity tasks",
    ],
    weaknesses: [
      "Limited public technical transparency",
      "API ecosystem still immature",
      "Availability may be restricted or waitlist-based",
    ],
    models: [
      {
        name: "Manus Agent",
        description:
          "General autonomous agent system for planning and executing complex digital tasks.",
      },
      {
        name: "Research Workflow Engine",
        description:
          "Specialized workflow layer for browsing, summarization, and structured research tasks.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
  },
  {
    id: "v0",
    slug: "v0",
    name: "v0",
    company: "Vercel",
    logo: "v0.svg",
    accentColor: "#000000",
    shortDescription:
      "AI-powered UI and app generation platform for building React and Next.js applications from natural language prompts.",
    description:
      "v0 is Vercel's AI-assisted development platform that generates React components, interfaces, and full-stack Next.js applications from text prompts, screenshots, and design references. It focuses on rapid frontend development, production-ready code generation, and seamless integration with the Vercel ecosystem.",
    categories: ["coding"],
    tags: ["ai-coding", "frontend", "react", "nextjs", "ui-generation", "chat"],
    bestFor: [
      "Frontend development",
      "Rapid prototyping",
      "Next.js applications",
      "Landing pages",
      "Internal tools",
      "AI-assisted UI design",
    ],
    pricing: {
      free: true,
      paid: true,
      notes:
        "Free tier available with usage limits, plus premium team and enterprise plans.",
    },
    apiAvailable: true,
    openSource: false,
    website: "https://v0.dev",
    documentation: "https://vercel.com/docs/v0",
    strengths: [
      "Excellent React and Next.js code generation",
      "Strong Tailwind and shadcn/ui integration",
      "Fast UI prototyping workflows",
      "Tight integration with Vercel deployment platform",
      "Supports screenshot and design-based generation",
    ],
    weaknesses: [
      "Primarily optimized for React ecosystem",
      "Generated code often requires manual refinement",
      "Advanced workflows can become expensive",
      "Backend capabilities less mature than frontend generation",
    ],
    models: [
      {
        name: "v0 UI Generator",
        description:
          "Core model for generating React components and responsive UI layouts from prompts.",
      },
      {
        name: "v0 App Builder",
        description:
          "Agent-oriented workflow system for scaffolding and iterating on full-stack Next.js applications.",
      },
      {
        name: "v0 Design Mode",
        description:
          "Visual editing and refinement layer for AI-generated interfaces and layouts.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
  },
  {
    id: "bolt-new",
    slug: "bolt-new",
    name: "Bolt.new",
    company: "StackBlitz",
    logo: "bolt.svg",
    accentColor: "#f59e0b",
    shortDescription:
      "AI-powered full-stack application builder that generates, runs, edits, and deploys web apps directly in the browser.",
    description:
      "Bolt.new is StackBlitz’s autonomous AI web development platform that allows users to generate, run, edit, and deploy full-stack applications entirely in the browser using natural language prompts. Built on StackBlitz WebContainers technology, Bolt.new provides a real runtime environment with Node.js, package installation, backend execution, live preview, and deployment workflows without requiring local setup.",
    categories: ["coding"],
    tags: [
      "ai-coding",
      "full-stack",
      "web-development",
      "agents",
      "browser-ide",
      "nextjs",
      "react",
      "webcontainers",
      "rapid-prototyping",
      "deployment",
    ],
    bestFor: [
      "Full-stack web app generation",
      "Rapid MVP prototyping",
      "Browser-based development",
      "AI-assisted coding workflows",
      "Startup product iteration",
      "Non-technical app building",
    ],
    pricing: {
      free: true,
      paid: true,
      notes:
        "Free tier available with usage limits, plus Pro, Teams, and Enterprise plans.",
    },
    apiAvailable: false,
    openSource: false,
    website: "https://bolt.new",
    documentation: "https://support.bolt.new",
    strengths: [
      "Runs full-stack apps directly in the browser",
      "Real Node.js runtime via WebContainers",
      "Supports package installation and backend execution",
      "Fast prompt-to-app workflow",
      "Integrated deployment and preview experience",
      "Excellent for rapid prototyping and MVPs",
    ],
    weaknesses: [
      "Complex production apps still require manual engineering",
      "Generated architecture may need refactoring",
      "Heavy projects can hit browser resource limits",
      "Backend/database workflows are less mature than traditional stacks",
    ],
    models: [
      {
        name: "Claude Sonnet",
        description:
          "Primary coding-focused reasoning model used for app generation and autonomous development workflows.",
      },
      {
        name: "GPT-4o",
        description:
          "Optional multimodal model support for coding and interface generation tasks.",
      },
      {
        name: "Gemini",
        description:
          "Alternative model option available for selected coding and workflow tasks.",
      },
      {
        name: "Bolt Agent Runtime",
        description:
          "Environment orchestration layer that manages files, terminals, dependencies, previews, and deployment workflows.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
    metadata: {
      browserBasedRuntime: true,
      supportsNodeJs: true,
      supportsPackageManagers: true,
      deploymentIntegrated: true,
      openSourceCoreAvailable: true,
    },
  },
  {
    id: "pomelli-ai",
    slug: "pomelli-ai",
    name: "Pomelli AI",
    company: "Google Labs",
    logo: "googleaistudio.svg",
    accentColor: "#4285f4",
    shortDescription:
      "AI-powered marketing and brand-content platform that generates on-brand campaigns, visuals, and social assets using Business DNA analysis.",
    description:
      "Pomelli AI is an experimental AI marketing platform developed through Google Labs and DeepMind initiatives. It analyzes a company’s website, assets, and brand identity to build a persistent 'Business DNA' profile that powers automated generation of social media campaigns, ad creatives, marketing copy, and branded visual assets while maintaining consistent tone, style, and visual identity across channels.",
    categories: ["text-generation", "image-generation"],
    tags: [
      "marketing",
      "branding",
      "social-media",
      "brand-dna",
      "campaign-generation",
      "content-creation",
      "design",
      "google-labs",
      "creative-ai",
      "ads",
    ],
    bestFor: [
      "Marketing campaign generation",
      "Social media content",
      "Brand-consistent creative assets",
      "SMB marketing automation",
      "Ad creative generation",
      "AI-assisted branding workflows",
    ],
    pricing: {
      free: true,
      paid: false,
      notes:
        "Currently available as a free public beta in selected regions during experimental rollout.",
    },
    apiAvailable: false,
    openSource: false,
    website: "https://labs.google.com/pomelli",
    documentation: "https://labs.google.com/pomelli",
    strengths: [
      "Strong brand-consistency system via Business DNA profiling",
      "Combines text and visual marketing generation",
      "Designed specifically for SMB marketing workflows",
      "Automates cross-platform campaign adaptation",
      "Integrated visual identity extraction from websites",
    ],
    weaknesses: [
      "Experimental product with limited regional availability",
      "Limited developer ecosystem and integrations",
      "Less flexible for non-marketing workflows",
      "Public technical architecture details remain limited",
    ],
    models: [
      {
        name: "Business DNA Engine",
        description:
          "Core brand-analysis system that extracts visual identity, tone, typography, and messaging patterns from websites and assets.",
      },
      {
        name: "Campaign Generator",
        description:
          "AI workflow layer for generating multi-platform marketing campaigns, social posts, and ad creatives.",
      },
      {
        name: "Visual Creative Generator",
        description:
          "Image-generation system optimized for branded marketing visuals and promotional assets.",
      },
      {
        name: "DeepMind Marketing Models",
        description:
          "Underlying multimodal AI systems powering language understanding, visual analysis, and content generation workflows.",
      },
    ],
    featured: false,
    trending: true,
    lastUpdated: "2026-05-14",
    metadata: {
      businessDnaSystem: true,
      multimodalGeneration: true,
      socialMediaFocused: true,
      publicBeta: true,
      regionRestricted: true,
      developedWithDeepMind: true,
    },
  },
  {
    id: "stitch-ai",
    slug: "stitch-ai",
    name: "Stitch",
    company: "Google Labs",
    logo: "googleaistudio.svg",
    accentColor: "#4285f4",
    shortDescription:
      "AI-powered UI and frontend generation platform that turns prompts, sketches, and screenshots into app designs and production-ready frontend code.",
    description:
      "Stitch is Google Labs’ AI-native UI design and frontend generation platform focused on transforming natural language prompts, sketches, wireframes, screenshots, and voice instructions into responsive app interfaces and frontend code. Built on Gemini models and evolved from Google’s acquisition of Galileo AI, Stitch combines design ideation, multi-screen prototyping, visual editing, and exportable frontend generation into a unified workflow for developers, designers, founders, and rapid product teams.",
    categories: ["coding"],
    tags: [
      "ui-generation",
      "frontend",
      "design-to-code",
      "react",
      "figma",
      "prototyping",
      "web-development",
      "mobile-ui",
      "gemini",
      "google-labs",
      "vibe-coding",
      "ai-design",
    ],
    bestFor: [
      "UI prototyping",
      "Frontend generation",
      "Design-to-code workflows",
      "Rapid app ideation",
      "Landing page generation",
      "Multi-screen app prototyping",
    ],
    pricing: {
      free: true,
      paid: false,
      notes:
        "Currently available as a free experimental product through Google Labs.",
    },
    apiAvailable: false,
    openSource: false,
    website: "https://stitch.withgoogle.com",
    documentation: "https://labs.google/stitch",
    strengths: [
      "Excellent prompt-to-UI generation",
      "Supports sketches, screenshots, and multimodal inputs",
      "Exports frontend code and Figma-compatible assets",
      "Fast multi-screen prototyping workflows",
      "Powered by advanced Gemini models",
      "Strong integration between design and frontend generation",
    ],
    weaknesses: [
      "Still experimental and evolving rapidly",
      "Primarily focused on frontend/UI workflows",
      "Complex production apps still require engineering refinement",
      "Limited backend orchestration compared to full AI app builders",
    ],
    models: [
      {
        name: "Gemini 2.5 Pro",
        description:
          "Advanced multimodal reasoning model used for high-quality UI generation, design interpretation, and frontend code synthesis.",
      },
      {
        name: "Gemini 2.5 Flash",
        description:
          "Faster lightweight model optimized for rapid UI ideation and iterative prototyping workflows.",
      },
      {
        name: "Stitch Design Engine",
        description:
          "AI-native design orchestration system that converts prompts, sketches, screenshots, and voice inputs into responsive interfaces and component systems.",
      },
      {
        name: "Stitch Multi-Screen Canvas",
        description:
          "Interactive prototyping layer for generating connected app flows, design systems, and exportable frontend experiences.",
      },
    ],
    featured: true,
    trending: true,
    lastUpdated: "2026-05-14",
    metadata: {
      supportsSketchInput: true,
      supportsScreenshotInput: true,
      figmaExport: true,
      frontendCodeExport: true,
      multimodalInput: true,
      experimentalProduct: true,
      developedByGoogleLabs: true,
      supportsVoicePrompting: true,
    },
  },
];
